- thirdeye-ui/src/app/components/app-bar/app-bar.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
> feat(ui): add support icon in nav with link

- thirdeye-ui/src/app/components/alert-wizard-v2/alert-details/alert-frequency/alert-date-time-cron-advance/alert-date-time-cron-advance.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-details/alert-frequency/alert-date-time-cron-advance/alert-date-time-cron-advance.test.tsx
- thirdeye-ui/src/app/rest/datasources/datasources.rest.test.ts
- thirdeye-ui/src/app/routers/alerts/alerts.router.test.tsx
- thirdeye-ui/src/app/routers/alerts/alerts.router.tsx
- thirdeye-ui/src/app/utils/routes/routes.util.test.ts
- thirdeye-ui/src/app/utils/routes/routes.util.ts
> test(ui): fix broken unit tests

- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-renderer/subscription-group-renderer.component.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-wizard.component.tsx
This PR refactors layout for the ultimate change which is support for Slack and Webhook in addition to email
Old
New
> refactor(ui): refactor layout of creating subscription group

- thirdeye-ui/package-lock.json
- thirdeye-ui/package.json
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/email/email.component.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/email/email.interfaces.ts
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/groups-editor.component.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/groups-editor.interfaces.ts
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/groups-editor.utils.ts
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/sendgrid-email/sendgrid-email.component.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/sendgrid-email/sendgrid-email.interfaces.ts
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/sendgrid-email/sendgrid-email.test.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/slack/slack.component.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/slack/slack.interfaces.ts
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/slack/slack.test.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/webhook/webhook.component.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/webhook/webhook.interfaces.ts
- thirdeye-ui/src/app/components/subscription-group-wizard/groups-editor/webhook/webhook.test.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-wizard.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/rest/dto/subscription-group.interfaces.ts
Add support for adding slack and webhook for notification
Landing page for creating subscription:
Page with multiple items added and Alerts panel expanded:
> feat(ui): support slack and webhook for notifications

- thirdeye-ui/src/app/components/alert-wizard/alert-wizard.component.tsx
- thirdeye-ui/src/app/components/anomaly-feedback/anomaly-feedback.component.tsx
- thirdeye-ui/src/app/components/anomaly-feedback/anomaly-feedback.interfaces.ts
- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.component.tsx
- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.test.tsx
- thirdeye-ui/src/app/components/rca/anomaly-time-series-card/anomaly-time-series-card.component.tsx
- thirdeye-ui/src/app/components/visualizations/alert-evaluation-time-series-card/alert-evaluation-time-series-card.component.tsx
- thirdeye-ui/src/app/components/visualizations/alert-evaluation-time-series-card/alert-evaluation-time-series-card.interfaces.ts
- thirdeye-ui/src/app/components/visualizations/alert-evaluation-time-series-card/headers/create-alert-header.component.tsx
- thirdeye-ui/src/app/components/visualizations/alert-evaluation-time-series-card/headers/view-anomaly-header.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx
- thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-page.component.tsx
- thirdeye-ui/src/app/pages/root-cause-analysis-investigation-state-tracker/investigation-state-tracker.component.tsx
- thirdeye-ui/src/app/platform/components/dropdown-button-v1/dropdown-button-v1.interfaces.ts
- thirdeye-ui/src/app/utils/anomalies/anomalies.util.ts
Refactoring to make the feedback widget more obvious and welcoming to use
Before Changes
After Changes:
> feat(ui): make feedback prompt more welcoming to use

- thirdeye-core/src/main/java/ai/startree/thirdeye/util/TemplateEngineTemplatableSerializer.java
- thirdeye-core/src/test/java/ai/startree/thirdeye/util/StringTemplateUtilsTest.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/components/EventDataFetcher.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/spec/EventFetcherSpec.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/rca/RcaInfoFetcher.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/json/TestTemplatableSerialization.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/rca/RcaInfoFetcherTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/RcaResourceTest.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/Templatable.java
- thirdeye-spi/src/test/java/ai/startree/thirdeye/spi/detection/AbstractSpecTest.java
> [spi] refactor templatable - better api

- thirdeye-ui/src/app/components/alert-list-v1/alert-list-v1.component.tsx
- thirdeye-ui/src/app/components/alert-list-v1/alert-list-v1.interfaces.ts
- thirdeye-ui/src/app/components/alert-list-v1/alert-list-v1.test.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/alerts-all-page/alerts-all-page.component.tsx
- thirdeye-ui/src/app/rest/alerts/alerts.actions.test.ts
- thirdeye-ui/src/app/rest/alerts/alerts.actions.ts
- thirdeye-ui/src/app/rest/alerts/alerts.interfaces.ts
- thirdeye-ui/src/app/rest/alerts/alerts.rest.test.ts
- thirdeye-ui/src/app/rest/alerts/alerts.rest.ts
Adding feature as well as cleaning up unused code (`onChange`)
> feat(ui): reset alert from all alerts page

- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-properties-builder/alert-template-properties-builder.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-properties-builder/alert-template-properties-builder.interfaces.ts
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.utils.test.ts
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.utils.ts
- thirdeye-ui/src/app/rest/dto/alert.interfaces.ts
- thirdeye-ui/src/app/utils/alerts/alerts.util.ts
Fix for https://cortexdata.atlassian.net/browse/TE-817
There are no changes on the UI side
> fix(ui): allow empty arrays and boolean in template properties

- thirdeye-ui/package-lock.json
- thirdeye-ui/package.json
- thirdeye-ui/src/app/components/visualizations/treemap/treemap-rect.component.tsx
- thirdeye-ui/src/app/components/visualizations/treemap/treemap.component.tsx
- thirdeye-ui/src/app/components/visualizations/treemap/treemap.interfaces.ts
- thirdeye-ui/src/app/components/visualizations/treemap/treemap.styles.ts
- thirdeye-ui/src/app/utils/visualization/visualization.util.test.ts
- thirdeye-ui/src/app/utils/visualization/visualization.util.ts
Using a library to determine whether to use `white` or `black` font color depending on the background color. Also refactored the the TreeMap so that the rectangle is its own component
> fix(ui): address enhancement feedback for heatmap

- thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/AnomalyLabelMapper.java
- thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/AnomalyMapper.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AnomalyApi.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AnomalyLabelApi.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/AnomalyLabelDTO.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/MergedAnomalyResultDTO.java
- thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/runner/AnomalyMerger.java
- thirdeye-worker/src/test/java/ai/startree/thirdeye/worker/task/runner/AnomalyMergerTest.java
See design doc: 
https://docs.google.com/document/d/1YVsTY_c0RFZBKYz757M9aEboYB5kixppgRvqbJmsZ04/edit#
This is the implementation of Step 1.
It introduces anomaly labels. 
Labels can be used to filter anomalies. 
Eg: filter anomalies that have the label “cold-start”.
> [spi] add anomaly labels

- thirdeye-ui/src/app/components/anomalies-page-header/anomalies-page-header.component.tsx
- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.component.tsx
- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.test.tsx
- thirdeye-ui/src/app/components/anomaly-quick-filters/anomaly-quick-filters.component.tsx
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-expand-list/metrics-report-expand-list.component.tsx
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-expand-list/metrics-report-expand-list.interface.ts
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-list.component.tsx
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-list.interfaces.ts
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-list.styles.ts
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-list.utils.ts
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-row/metrics-report-row.component.tsx
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-row/metrics-report-row.interface.ts
- thirdeye-ui/src/app/components/rca/anomaly-time-series-card/anomaly-time-series-card.utils.tsx
- thirdeye-ui/src/app/components/visualizations/metrics-report-evaluation-time-series/metrics-report-evaluation-time-series.interface.ts
- thirdeye-ui/src/app/components/visualizations/metrics-report-evaluation-time-series/metrics-report-evalution-time-series.component.tsx
- thirdeye-ui/src/app/pages/anomalies-all-page/anomalies-all-page.component.tsx
- thirdeye-ui/src/app/pages/anomalies-all-page/anomalies-all-page.interfaces.ts
- thirdeye-ui/src/app/pages/anomalies-list-page/anomalies-list-page.component.tsx
- thirdeye-ui/src/app/pages/anomalies-metrics-report-page/anomalies-metrics-report-page.component.tsx
- thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-page.component.tsx
- thirdeye-ui/src/app/rest/dto/anomaly.interfaces.ts
- thirdeye-ui/src/app/routers/anomalies/anomalies.router.tsx
Updating the all anomalies page into 2 different views. The original table view and the "Metrics List" view
https://cortexdata.atlassian.net/browse/TE-518
> feat(ui): TE-518 all anomalies page view updates

- pom.xml
- thirdeye-core/pom.xml
- thirdeye-dataframe/src/main/java/ai/startree/thirdeye/spi/dataframe/DataFrame.java
> [mvn] remove unused dependencies

- thirdeye-core/src/main/java/ai/startree/thirdeye/datasource/calcite/QueryProjection.java
- thirdeye-core/src/main/java/ai/startree/thirdeye/datasource/loader/DefaultAggregationLoader.java
- thirdeye-core/src/main/java/ai/startree/thirdeye/datasource/loader/DefaultMinMaxTimeLoader.java
- thirdeye-core/src/main/java/ai/startree/thirdeye/util/CalciteUtils.java
- thirdeye-core/src/test/java/ai/startree/thirdeye/datasource/calcite/CalciteRequestTest.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/rca/CohortComputation.java
quickfixes
need proper refactoring
> [core] fix calcite request dimension identifier quoting

- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/DropwizardTestUtils.java
- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/PinotContainerManager.java
- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/SchedulingTest.java
- thirdeye-integration-tests/src/test/resources/happypath/payloads/startree-absolute-rule-alert.json
- thirdeye-integration-tests/src/test/resources/happypath/payloads/startree-absolute-rule-percentile-alert.json
- thirdeye-integration-tests/src/test/resources/happypath/payloads/startree-mean-variance-alert.json
- thirdeye-integration-tests/src/test/resources/happypath/payloads/startree-mean-variance-percentile-alert.json
- thirdeye-integration-tests/src/test/resources/happypath/payloads/startree-percentage-rule-alert.json
- thirdeye-integration-tests/src/test/resources/happypath/payloads/startree-percentage-rule-percentile-alert.json
- thirdeye-integration-tests/src/test/resources/happypath/payloads/startree-threshold-alert.json
- thirdeye-integration-tests/src/test/resources/happypath/payloads/startree-threshold-percentile-alert.json
> [integration-tests] add template integration tests

- pinot-test-container/src/main/java/org/apache/pinot/testcontainer/PinotContainer.java
diff is broken by some auto formatting :/ 
keeping the formatting in the same PR, changes are minor
> [pinot-test-container] upgrade pinot version from 0.9.3 to 0.11.0

- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/PlanNodeFactory.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/PostProcessorRegistry.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/operator/DetectionPipelineOperator.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/operator/PostProcessorOperator.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/plan/PostProcessorPlanNode.java
- thirdeye-detectionpipeline/src/test/java/ai/startree/thirdeye/detectionpipeline/operator/PostProcessorOperatorTest.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/Constants.java
first step - move some logic in the registry - in particular daos that can be injected
next step: use factory pattern, remove init and specClass method
> [detectionpipeline] refactor postProcessorRegistry

- pinot-test-container/src/main/java/org/apache/pinot/testcontainer/PinotContainer.java
Use the arm64 pinot container when running unit tests on an M1 laptop.
> mac m1s use arm64 pinot container

- pom.xml
https://cortexdata.atlassian.net/browse/TE-345
UI project is in the middle of some configuration updates. As a result, some files are missing license headers. THis is a temporary fix to avoid build failure.
> Disable license header check for UI project

- .github/CODEOWNERS
- thirdeye-ui/.prettierignore
https://cortexdata.atlassian.net/browse/TE-345
Updated repo configurations and code owners
> chore(ui): TE-345 updated CODEOWNERS

- .github/CODEOWNERS
https://cortexdata.atlassian.net/browse/TE-345
This change introduces an exception in CODEOWNERS to allow [thirdeye-ci](https://github.com/orgs/startreedata/people/thirdeye-ci) bot to update pom.xml file in UI project.
> chore(ui): TE-345 update CODEOWNERS to fix build failures

- thirdeye-ui/release.config.js
https://cortexdata.atlassian.net/browse/TE-1046
Removing the hardcoded slack webhook
> chore(ui): TE-1046 remove hardcoded slack webhook

- .github/CODEOWNERS
- thirdeye-ui/.gitignore
- thirdeye-ui/.prettierignore
https://cortexdata.atlassian.net/browse/TE-345
Bot doesn't care about Prettier formatting. :(
Also bringing back the CODEOWNERS.
> chore(ui): TE-345 bot updated pom.xml excluded from formatting checks to pass the build

- thirdeye-ui/release.config.js
https://cortexdata.atlassian.net/browse/TE-1046
Matching the rest of the startre-ui projects
> chore(ui): TE-1046 use SLACK_PUBLISH_WEBHOOK instead of SLACK_NOTIFICATION_WEBHOOK

- thirdeye-ui/release.config.js
https://cortexdata.atlassian.net/browse/TE-1046
Slack webhook for release notification moved to environment variable.
> chore(ui): TE-1046 slack webhook for release notification moved to environment var

- thirdeye-ui/src/app/routers/general-authenticated/general-authenticated.router.tsx
- thirdeye-ui/src/app/utils/routes/routes.util.ts
- [TE-1051](https://cortexdata.atlassian.net/browse/TE-1051)
Change routing name `/cohort-detector` to `/cohort-recommender` to be more consistent with the page title
> fix(ui): TE-1051 renamed cohort-detector route to be consistent with page title 

- thirdeye-core/src/main/java/ai/startree/thirdeye/calcite/dataframe/DataFrameEnumerator.java
- thirdeye-dataframe/src/main/java/ai/startree/thirdeye/spi/dataframe/DataFrame.java
- thirdeye-dataframe/src/test/java/ai/startree/thirdeye/spi/dataframe/DataFrameTest.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/operator/EventTriggerOperator.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/operator/sql/HyperSqlDataTableToSqlAdapter.java
- thirdeye-detectionpipeline/src/test/java/ai/startree/thirdeye/detectionpipeline/components/TimeIndexFillerTest.java
- thirdeye-detectionpipeline/src/test/java/ai/startree/thirdeye/detectionpipeline/operator/SqlExecutionOperatorTest.java
- thirdeye-plugins/thirdeye-detection-components/src/main/java/ai/startree/thirdeye/plugins/detection/components/triggers/ConsoleOutputTrigger.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/ThirdEyeResultSetDataTable.java
- thirdeye-plugins/thirdeye-postprocessors/src/test/java/ai/startree/thirdeye/plugins/postprocessor/ColdStartPostProcessorTest.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/EventTrigger.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/v2/DataTable.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/v2/SimpleDataTable.java
- [spi] simplify SimpleDataTable interface
- clean
- [spi] simplify DataTable interface
- [spi] simplify DataTable interface
> simplify data table 2

- thirdeye-ui/.gitignore
- thirdeye-ui/.licenseheaderignore
https://cortexdata.atlassian.net/browse/TE-1076
Ignored IDE files from license header check.
> chore(ui): TE-1076 ignored IDE files from license header check

- thirdeye-plugins/thirdeye-detectors/src/main/java/ai/startree/thirdeye/plugins/detectors/AbsoluteChangeRuleDetector.java
- thirdeye-plugins/thirdeye-detectors/src/main/java/ai/startree/thirdeye/plugins/detectors/MeanVarianceRuleDetector.java
- thirdeye-plugins/thirdeye-detectors/src/main/java/ai/startree/thirdeye/plugins/detectors/PercentageChangeRuleDetector.java
- thirdeye-plugins/thirdeye-detectors/src/main/java/ai/startree/thirdeye/plugins/detectors/ThresholdRuleDetector.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/v2/DataTable.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/v2/SimpleDataTable.java
similar changes required in internal distribution
> [spi] remove protective copy in SimpleDataTable

- thirdeye-ui/src/app/components/alert-wizard-v3/algorithm-selection/algorithm-selection.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-alert/select-type/select-type-page.component.tsx
https://cortexdata.atlassian.net/browse/TE-1112
In the community edition, an entire section can be missing when picking an algorithm. Show a user friendly message about it
> fix(ui): TE-1112 show empty message when alert templates for a section is missing

- thirdeye-ui/docker/templates/default.conf.template
Add no cache header and 1hr expiration
> chore(ui): TE-1114 add header to not cache index.html

- thirdeye-ui/src/app/app.tsx
- thirdeye-ui/src/app/components/app-bar/app-bar-config-provider/app-bar-config-provider.component.tsx
- thirdeye-ui/src/app/components/app-bar/app-bar-config-provider/app-bar-config-provider.interface.ts
- thirdeye-ui/src/app/pages/welcome-page/create-alert/create-alert-page.component.tsx
- thirdeye-ui/src/app/routers/welcome/welcome.router.tsx
https://cortexdata.atlassian.net/browse/TE-1111
Hiding the navigation bar when the welcome route is loaded. This requires providing a context that keeps track of showNavbar flag
> refactor(ui): TE-1111 hide navbar in welcome flow

- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.style.ts
- [TE-1120](https://cortexdata.atlassian.net/browse/TE-1120)
- Added intro video to welcome screen
- Video URL: https://www.youtube.com/watch?v=XhaLcpiPUS0
> feat(ui): TE-1120 added intro video to welcome screen

- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/preview-chart.component.tsx
https://cortexdata.atlassian.net/browse/TE-1158
Ensure the insights API is hit again when start and end is missing
No UI changes
> fix(ui): TE-1158 ensure valid start and end exist when fetching data

- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/welcome-page/create-alert/select-type/select-type-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-alert/select-type/select-type-page.interface.ts
- thirdeye-ui/src/app/routers/alerts-guided-create/alerts-guided-create.router.tsx
https://cortexdata.atlassian.net/browse/TE-1153
For situations where users will create multiple of the same sample alerts, we need to append random 3 character strings so they can successfully be created
> fix(ui): TE-1153 append random 3 character string to sample alert name when creating

- thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup.component.tsx
https://cortexdata.atlassian.net/browse/TE-1157
Fixing white screen issue where invalid json from the Advanced Editor button breaks UI.
No changes to the UI
> fix(ui): TE-1157 fix bug where invalid json will cause white screen

- thirdeye-ui/src/app/components/anomalies-page-header/anomalies-page-header.component.tsx
- thirdeye-ui/src/app/components/filter-options-auto-complete/filter-options-auto-complete.component.tsx
- thirdeye-ui/src/app/components/home-page/recent-anomalies/recent-anomalies.component.tsx
- thirdeye-ui/src/app/components/visualizations/time-series-chart/chart-core/chart-core.component.tsx
- thirdeye-ui/src/app/components/visualizations/time-series-chart/tooltip/tooltip-markers.component.tsx
- thirdeye-ui/src/app/components/visualizations/time-series-chart/tooltip/tooltip-popover.component.tsx
- thirdeye-ui/src/app/pages/anomalies-all-page/anomalies-all-page.component.tsx
[TE-1163](https://cortexdata.atlassian.net/browse/TE-1163)
Fixed various minor issues throwing a console error during development mode
[TE-1163]: https://cortexdata.atlassian.net/browse/TE-1163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): TE-1163 browser console cleanup for ThirdEye UI

- thirdeye-ui/jest.config.js
- thirdeye-ui/package-lock.json
- thirdeye-ui/package.json
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-form-field/alert-template-form-field.component.tsx
- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.test.tsx
- thirdeye-ui/src/app/components/parse-markdown/parse-markdown.component.tsx
- thirdeye-ui/src/app/components/parse-markdown/parse-markdown.interfaces.ts
[TE-1149](https://cortexdata.atlassian.net/browse/TE-1149)
- Added markdown support in form helper tooltip in alert create form
- Using [react-markdown](https://github.com/remarkjs/react-markdown) in a common component to enable markdown support
[TE-1149]: https://cortexdata.atlassian.net/browse/TE-1149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TE-1149]: https://cortexdata.atlassian.net/browse/TE-1149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): TE-1149 add markdown support in alert create form helper tooltip

- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/AnomalyResource.java
https://cortexdata.atlassian.net/browse/TE-1187
Endpoint on anomaly resource to expose anomaly stats. Exposing this endpoint to support dashboard usecase.
endpoint : `/api/anomalies/stats`
response:
```
{
"totalCount": 100,
"countWithFeedback": 80,
"feedbackStats": {
"NO_FEEDBACK": 10,
"ANOMALY_EXPECTED": 20,
"ANOMALY": 30,
"ANOMALY_NEW_TREND": 10,
"NOT_ANOMALY": 10
}
}
```
The endpoint also accepts query params to filter the sample set of anomalies by startTime and endTime
example : `/api/anomalies/stats?startTime=1661970600000&endTime=1670344199999`
> [server] endpoint to expose anomaly stats with startTime and endTime filters

- thirdeye-ui/README.md
- thirdeye-ui/package.json
https://cortexdata.atlassian.net/browse/STUI-581
One can now use `npm run ci-check` script to locally execute all the scripts that CI validations will execute on a PR.
> chore(ui): STUI-581 create CI validation script

- thirdeye-core/src/main/java/ai/startree/thirdeye/alert/AlertTemplateRenderer.java
- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
- thirdeye-plugins/thirdeye-bootstrap-open-core/src/main/java/ai/startree/thirdeye/plugins/bootstrap/opencore/CommonProperties.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/CrudResourceTest.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/template/TemplatePropertyMetadata.java
- [bootstrap] box templateProperty booleans
- [bootstrap] update template properties to markdown
> update properties doc

- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.component.tsx
- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.interfaces.ts
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-expand-list/metrics-report-expand-list.component.tsx
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-expand-list/metrics-report-expand-list.interface.ts
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-row/metrics-report-row.component.tsx
- thirdeye-ui/src/app/pages/anomalies-list-page/anomalies-list-page.component.tsx
- thirdeye-ui/src/app/rest/dto/ui-anomaly.interfaces.ts
- thirdeye-ui/src/app/utils/anomalies/anomalies.util.ts
[TE-1203](https://cortexdata.atlassian.net/browse/TE-1203)
- Added enumeration item for anomalies entries and anomalies table and metrics report table
- Enumeration items data is fetched asynchronously and rendered after the main table
[TE-1203]: https://cortexdata.atlassian.net/browse/TE-1203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): TE-1203 added enumeration items to anomalies list table and metrics report table

- thirdeye-ui/src/app/components/admin-page/recent-failures/recent-failures.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-notifications/subscription-groups/subscription-groups.component.tsx
- thirdeye-ui/src/app/components/home-page/active-alerts-count/active-alerts-count.component.tsx
- thirdeye-ui/src/app/components/home-page/alert-accuracy/alert-accuracy.component.tsx
- thirdeye-ui/src/app/components/home-page/anomalies-pending-feedback-count/anomalies-pending-feedback-count.component.tsx
- thirdeye-ui/src/app/components/home-page/anomalies-reported-count/anomalies-reported-count.component.tsx
- thirdeye-ui/src/app/components/home-page/recent-anomalies/recent-anomalies.component.tsx
- thirdeye-ui/src/app/components/home-page/trending-anomalies/trending-anomalies.component.tsx
- thirdeye-ui/src/app/components/rca/anomaly-breakdown-comparison-heatmap/anomaly-breakdown-comparison-heatmap.component.tsx
- thirdeye-ui/src/app/pages/alerts-update-page/alerts-edit-base-page.component.tsx
- thirdeye-ui/src/app/pages/datasets-all-page/datasets-all-page.component.tsx
- thirdeye-ui/src/app/pages/datasources-all-page/datasources-all-page.component.tsx
- thirdeye-ui/src/app/pages/root-cause-analysis-for-anomaly-page/root-cause-analysis-for-anomaly-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-alert/create-alert-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasets/onboard-datasets-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasource/onboard-datasource-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.component.tsx
https://cortexdata.atlassian.net/browse/TE-1246
Ensuring the loading state will always be shown on a new page load
No UI changes
> chore(ui): TE-1246 check for initial loading state for LoadingErrorStateSwitch depending on requests

- thirdeye-ui/src/app/components/iframe-video-player-container/iframe-video-player-container.component.tsx
- thirdeye-ui/src/app/components/iframe-video-player-container/iframe-video-player-container.style.ts
- thirdeye-ui/src/app/components/rca/investigation-options/investigation-options.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.component.tsx
https://cortexdata.atlassian.net/browse/TE-1220
Adding button to open modal to show video of how to use the RCA tools
> feat(ui): TE-1220 link to rca demo video in rca and anomaly details page

- thirdeye-core/src/main/java/ai/startree/thirdeye/alert/AlertDetectionIntervalCalculator.java
- thirdeye-core/src/main/java/ai/startree/thirdeye/config/TimeConfiguration.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/calcite/filter/SqlFilterRunnerTest.java
- thirdeye-plugins/thirdeye-datasources/src/main/java/ai/startree/thirdeye/plugins/datasource/sql/SqlDataset.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotDatasetOnboarder.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/alert/AlertInsightsProvider.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/rca/CohortComputation.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/rca/HeatmapCalculator.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/rca/RcaInfo.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/rca/RcaInfoFetcher.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/RcaDimensionAnalysisResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/RcaRelatedResource.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/Constants.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/TimeColumnApi.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/Templatable.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/AbstractSpec.java
- [spi] enhance input sanity check for Templatable
- [spi] enforce a single default chronology constant
> clean fixmes

- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.component.tsx
- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.test.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
[TE-1225](https://cortexdata.atlassian.net/browse/TE-1225)
- Renamed the column label for Anomaly ID from `Name` to explicitly `Anomaly ID`
- Removed the redundant `Anomaly` from the `Anomaly #24601` name
- Added custom tooltips over each link to indicate what the link leads to
[TE-1225]: https://cortexdata.atlassian.net/browse/TE-1225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): TE-1225 make links in anomaly table more intuitive

- thirdeye-ui/src/app/components/rca/anomaly-dimension-analysis/algorithm-table/algorithm-row.component.tsx
- thirdeye-ui/src/app/components/rca/anomaly-dimension-analysis/algorithm-table/algorithm-table.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
[TE-1221](https://cortexdata.atlassian.net/browse/TE-1221)
- Added column header to `Add to chart` and `Show Details` column
- Made the `Show Details` expand arrow darker
[TE-1221]: https://cortexdata.atlassian.net/browse/TE-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): TE-1221 improved ui for top contributors in investigate anomalies

- thirdeye-ui/src/app/components/time-range/time-range-selector/date-time-picker-toolbar/date-time-picker-toolbar.component.tsx
https://cortexdata.atlassian.net/browse/TE-1216
Forgot add these changes for the toolbar to render the times in the right timezone
Refer to https://github.com/startreedata/thirdeye/pull/913
> chore(ui): TE-1216 add missing changes for PR-913

- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
- thirdeye-plugins/thirdeye-postprocessors/src/main/java/ai/startree/thirdeye/plugins/postprocessor/AnomalyMergerPostProcessor.java
- thirdeye-plugins/thirdeye-postprocessors/src/main/java/ai/startree/thirdeye/plugins/postprocessor/AnomalyMergerPostProcessorSpec.java
- thirdeye-plugins/thirdeye-postprocessors/src/test/java/ai/startree/thirdeye/plugins/postprocessor/AnomalyMergerPostProcessorTest.java
Implementation of Rule 1, 2, 3 and 3bis of the merging logic for mutable data doc: 
https://docs.google.com/document/d/1bSbv4XhTQsdGR1XVM_dYL1cK9Q6JlntvzNYmmMiXQRI/edit#
> implement anomaly replay merge logic 1, 2 and 3

- thirdeye-ui/src/app/components/rca/analysis-tabs/analysis-tabs.component.tsx
- thirdeye-ui/src/app/pages/alert-templates-create-page/alert-templates-create-page.component.tsx
- thirdeye-ui/src/app/pages/alert-templates-update-page/alert-templates-update-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-guided-page/select-type/select-type-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-base-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-update-page/alerts-update-base-page.component.tsx
- thirdeye-ui/src/app/pages/datasets-onboard-page/datasets-onboard-page.component.tsx
- thirdeye-ui/src/app/pages/datasets-update-page/datasets-update-page.component.tsx
- thirdeye-ui/src/app/pages/datasets-view-page/datasets-view-page.component.tsx
- thirdeye-ui/src/app/pages/datasources-create-page/datasources-create-page.component.tsx
- thirdeye-ui/src/app/pages/datasources-update-page/datasources-update-page.component.tsx
- thirdeye-ui/src/app/pages/datasources-view-page/datasources-view-page.component.tsx
- thirdeye-ui/src/app/pages/events-create-page/events-create-page.component.tsx
- thirdeye-ui/src/app/pages/events-view-page/events-view-page.component.tsx
- thirdeye-ui/src/app/pages/subscription-groups-create-page/subscription-groups-create-page.component.tsx
- thirdeye-ui/src/app/pages/subscription-groups-update-page/subscription-groups-update-page.component.tsx
https://cortexdata.atlassian.net/browse/TE-1102
Quick payment to tech debt. Some parts of the codebase were still not using `notifyIfErrors`
No changes to ui
> chore(ui): TE-1102 use notifyIfErrors across codebase

- thirdeye-ui/src/app/components/rca/analysis-tabs/analysis-tabs.component.tsx
- thirdeye-ui/src/app/components/rca/analysis-tabs/analysis-tabs.interfaces.ts
- thirdeye-ui/src/app/components/rca/anomaly-breakdown-comparison-heatmap/anomaly-breakdown-comparison-heatmap.interfaces.ts
- thirdeye-ui/src/app/components/rca/anomaly-dimension-analysis/algorithm-table/algorithm-row-expanded.component.tsx
- thirdeye-ui/src/app/components/rca/anomaly-dimension-analysis/algorithm-table/algorithm-row.component.tsx
- thirdeye-ui/src/app/components/rca/anomaly-dimension-analysis/algorithm-table/algorithm-table.component.tsx
- thirdeye-ui/src/app/components/rca/anomaly-dimension-analysis/algorithm-table/algorithm-table.interfaces.ts
- thirdeye-ui/src/app/components/rca/anomaly-dimension-analysis/anomaly-dimension-analysis.component.tsx
- thirdeye-ui/src/app/components/rca/anomaly-dimension-analysis/anomaly-dimension-analysis.interfaces.ts
- thirdeye-ui/src/app/components/rca/events-tab/event-tab.component.tsx
- thirdeye-ui/src/app/components/rca/events-tab/event-tab.interfaces.ts
- thirdeye-ui/src/app/pages/root-cause-analysis-for-anomaly-page/root-cause-analysis-for-anomaly-page.component.tsx
- thirdeye-ui/src/app/pages/root-cause-analysis-investigation-state-tracker/investigation-state-tracker.component.tsx
- thirdeye-ui/src/app/pages/root-cause-analysis-investigation-state-tracker/investigation-state-tracker.interfaces.ts
https://cortexdata.atlassian.net/browse/TE-1216
Supporting timezone display in RCA pages
> feat(ui): TE-1216 support timezone in rca pages

- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.interfaces.ts
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart.interfaces.ts
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/alerts-update-page/alerts-edit-base-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-update-page/alerts-update-advanced-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-update-page/alerts-update-page.interfaces.ts
- thirdeye-ui/src/app/pages/alerts-update-page/alerts-update-simple-page.component.tsx
https://cortexdata.atlassian.net/browse/TE-1239
> feat(ui): TE-1239 disable update button for alert until user previews changes

- thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx
https://cortexdata.atlassian.net/browse/TE-1233
Fixing issue where the notification would not be removed in some cases
No UI changes
> fix(ui): TE-1233 fix defect where notification indicating auto reload would not go away 

- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/enumeration-items-table/enumeration-item-row/enumeration-item-row.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/enumeration-items-table/enumeration-item-row/enumeration-item-row.interfaces.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/enumeration-items-table/enumeration-items-table.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/enumeration-items-table/enumeration-items-table.interfaces.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/preview-chart.component.tsx
https://cortexdata.atlassian.net/browse/TE-1216
Supporting timezone in alert configuration during the create flow
> feat(ui): TE-1216 create alert flow support timezone

- thirdeye-ui/.eslintrc.yaml
- thirdeye-ui/README.md
https://cortexdata.atlassian.net/browse/STUI-605
Keeping project configurations in sync with UI monorepo.
> chore(ui): STUI-605 sync monorepo and ThirdEye project configs

- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AnomalyManagerImpl.java
- thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/runner/DetectionPipelineTaskRunner.java
Set auth for child anomalies.
Fixup from https://github.com/startreedata/thirdeye/pull/898
> Copy auth to child anomalies

- thirdeye-ui/src/app/components/rca/anomaly-time-series-card/anomaly-time-series-card.utils.tsx
https://cortexdata.atlassian.net/browse/TE-1331
Missed filtering for y0 and y1
No UI changes
> fix(ui): TE-1331 add missing non number filter on upper and lower bound

- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/EnumerationItemManagerImpl.java
> [server] Bugfix. Fix incorrect migration of enumeration items from Subscription Group

- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/EnumerationItemManagerImpl.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/MaintenanceResource.java
> [server] Maintenance. EnumerationItem Migration fix

- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/MaintenanceResource.java
> [server] Maintenance. EnumerationItem Migration fix for subscription Group

- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/MaintenanceResource.java
> [server] Bugfix. Fix incorrect migration of enumeration items with null Alert

- thirdeye-core/src/test/java/ai/startree/thirdeye/mapper/ApiBeanMapperTest.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/RcaInvestigationResource.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/RcaInvestigationApi.java
When a new investigation is created, copy authorization config from the parent anomaly.
https://cortexdata.atlassian.net/browse/TE-1328
Tested by creating an investigation from ui w/ access control enabled.
> RCA Investigation gets a copy of the anomaly auth

- thirdeye-ui/release.config.js
https://cortexdata.atlassian.net/browse/STUI-615
Minor update to successful release Slack message text.
> chore(ui): STUI-615 updated successful release Slack message text

- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/RcaInvestigationManagerImpl.java
https://cortexdata.atlassian.net/browse/TE-1344
Introducing new metric to emit RCA investigation count
metric : `rcaInvestigationCount `
type : `CachedGauge `
cache timeout : 15 minutes
> [persistence] Metric to emit rca investigation count

- thirdeye-ui/src/app/components/visualizations/time-series-chart/time-series-chart.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-guided-page/alerts-create-guided-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-guided-page/alerts-create-guided-page.styles.ts
- thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-anomalies-filter/setup-anomalies-filter-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-anomalies-filter/setup-anomalies-filter-page.interface.ts
- thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-anomalies-filter/setup-anomalies-filter-page.styles.ts
- thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-details/setup-details-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-monitoring/setup-monitoring-page.component.tsx
- thirdeye-ui/src/app/routers/alerts-guided-create/alerts-guided-create.router.tsx
- thirdeye-ui/src/app/utils/routes/routes.util.ts
https://cortexdata.atlassian.net/browse/TE-1142
Integrating the anomalies filtering configuration components with new page component
> feat(ui): TE-1142 anomalies filtering in alert create for new user flow

- thirdeye-ui/jest.config.js
- thirdeye-ui/package-lock.json
- thirdeye-ui/package.json
- thirdeye-ui/src/app/platform/rest/info/info.actions.ts
- thirdeye-ui/src/app/platform/rest/openid-configuration/openid-configuration.actions.ts
- thirdeye-ui/src/app/platform/utils/axios/axios.util.test.ts
- thirdeye-ui/src/app/platform/utils/axios/axios.util.ts
- thirdeye-ui/src/app/rest/create-rest-action.ts
- thirdeye-ui/src/app/rest/rca/rca.rest.ts
https://cortexdata.atlassian.net/browse/TE-1206
Bump axios to latest
No UI changes
> chore(ui): TE-1206 bump axios to 1.3.4

- thirdeye-ui/src/app/components/subscription-group-view/alert-associations-view-table/alert-associations-view-table.utils.test.ts
- thirdeye-ui/src/app/components/subscription-group-view/alert-associations-view-table/alert-associations-view-table.utils.ts
- thirdeye-ui/src/app/components/subscription-group-wizard/alerts-dimensions/alerts-dimensions.utils.test.ts
[TE-1270](https://cortexdata.atlassian.net/browse/TE-1270)
Added unit tests for some utils files in subscription group revamp
None, just unit tests
[TE-1270]: https://cortexdata.atlassian.net/browse/TE-1270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(ui): TE-1206 added tests for some utils files for subscription group revamp

- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.utils.ts
[TE-1317](https://cortexdata.atlassian.net/browse/TE-1317)
Added `aggregationColumn` to `templateProperties` in new alert configuration. Works with other existing flows (simple and guided).
[TE-1317]: https://cortexdata.atlassian.net/browse/TE-1317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): TE-1317 added `aggregationColumn` to new alert configuration

- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.component.tsx
[TE-1305](https://cortexdata.atlassian.net/browse/TE-1305)
Added link to configuration section in the welcome flow.
[TE-1305]: https://cortexdata.atlassian.net/browse/TE-1305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): TE-1305 added link to config section in welcome flow

- thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup.utils.test.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup.utils.ts
- thirdeye-ui/src/app/pages/metrics-update-page/metrics-update-page.component.tsx
- thirdeye-ui/src/app/rest/dto/metric.interfaces.ts
- thirdeye-ui/src/app/rest/metrics/metrics.rest.ts
- thirdeye-ui/src/app/utils/bulk-delete/bulk-delete.util.ts
- thirdeye-ui/src/app/utils/datasources/datasources.util.ts
https://cortexdata.atlassian.net/browse/TE-1366
Adding virtual column (*) in order to use COUNT
> feat(ui): TE-1304 support count * as a metric

- thirdeye-ui/src/app/components/alert-wizard-v3/sample-alert-selection/sample-alert.utils.ts
- thirdeye-ui/src/app/locale/languages/en-us.json
https://cortexdata.atlassian.net/browse/TE-1377
Adding new sample alert selection
> feat(ui): TE-1377 add rideshare sample alert

- thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-page.component.tsx
https://cortexdata.atlassian.net/browse/TE-1412
Using `evaluation?.alert.template`
No changes to UI
> fix(ui): TE-1412 use insights api to derive timezone for anomaly chart

- thirdeye-ui/src/app/routers/anomalies/anomalies.router.tsx
https://cortexdata.atlassian.net/browse/TE-1399
Removing the cancel API as a stop gap solution
No ui changes
> fix(ui): TE-1399 fix canceled apis when using filters for anomalies

- thirdeye-ui/CHANGELOG.md
https://cortexdata.atlassian.net/browse/TE-1441
Removing entry due to failure of artifact being generated
no ui changes
> feat(ui): TE-1441 remove 2.13.1 entry in changelog and forcing new version

- thirdeye-ui/src/app/components/anomalies-page-header/anomalies-page-header.component.tsx
- thirdeye-ui/src/app/components/help-drawer-v1/help-drawer-v1.component.tsx
- thirdeye-ui/src/app/components/help-drawer-v1/help-drawer-v1.interfaces.ts
- thirdeye-ui/src/app/components/rca/investigation-options/investigation-options.component.tsx
- thirdeye-ui/src/app/pages/alerts-all-page/alerts-all-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-update-page/alerts-edit-base-page.component.tsx
- thirdeye-ui/src/app/pages/anomalies-create-page/anomalies-create-page.component.tsx
- thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-page.component.tsx
https://cortexdata.atlassian.net/browse/TE-1450
Refactor to move state management inside the component. Added required `trigger` param for button to be housed in
No UI changes
> refactor(ui): TE-1450 helpdrawerv1 maintain isopen state

- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-form-field/form-component-for-template-field/form-component-for-template-field.component.tsx
https://cortexdata.atlassian.net/browse/TE-1451
Have the UI show the state of the default if there is no value set
> fix(ui): TE-1451 boolean type field take show state of default value if no value set

- thirdeye-ui/src/app/components/alert-wizard-v3/sample-alert-selection/sample-alert.utils.ts
https://cortexdata.atlassian.net/browse/TE-1492
Sinply adding link
> feat(ui): TE-1492 add link to recipe for ads monitoring sample alert

- thirdeye-ui/src/app/pages/welcome-page/create-alert/create-alert-page.component.tsx
https://cortexdata.atlassian.net/browse/TE-1495
Fixing bug introduced with recent feature changes.
No UI change
> fix(ui): TE-1495 fix bug where alert name was not being passed to POST

- thirdeye-ui/src/app/routers/alerts/alerts.router.tsx
- thirdeye-ui/src/app/routers/subscription-groups/subscription-groups-create-edit.router.interface.ts
- thirdeye-ui/src/app/routers/subscription-groups/subscription-groups-create-edit.router.tsx
- thirdeye-ui/src/app/routers/subscription-groups/subscription-groups.router.tsx
https://cortexdata.atlassian.net/browse/TE-1371
Make the routing share the same components
No UI changes
> refactor(ui): TE-1371 make routing for create and update use same component

- thirdeye-ui/src/app/components/anomalies-view/chart/chart.component.tsx
- thirdeye-ui/src/app/components/anomalies-view/chart/chart.interfaces.ts
- thirdeye-ui/src/app/components/anomalies-view/page-skeleton/page-skeleton.component.tsx
https://cortexdata.atlassian.net/browse/TE-1471
Skeleton loader
Chart with date time picker variant
Chart with duration picker variant
> feat(ui): TE-1471 anomaly view chart and page skeleton component

- thirdeye-ui/src/app/routers/subscription-groups/subscription-groups-create-edit.router.test.tsx
- thirdeye-ui/src/app/routers/subscription-groups/subscription-groups-create-edit.router.tsx
- thirdeye-ui/src/app/routers/subscription-groups/subscription-groups.router.test.tsx
- thirdeye-ui/src/app/routers/subscription-groups/subscription-groups.router.tsx
https://cortexdata.atlassian.net/browse/TE-1371
Adding test cases for the create edit router and enhancing tests for main subscription group router
No UI changes
> test(ui): TE-1371 add tests for subscription group routers

- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/recipient-details/groups-editor/email/email.component.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/recipient-details/groups-editor/groups-editor.component.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/recipient-details/recipient-details.component.tsx
- thirdeye-ui/src/app/rest/dto/subscription-group.interfaces.ts
- thirdeye-ui/src/app/utils/subscription-groups/subscription-groups.util.ts
https://cortexdata.atlassian.net/browse/TE-1507
`notificationSchemes` tuns out to be an optional field
No UI changes
> fix(ui): TE-1507 account for missing `notificationSchemes` field

- thirdeye-ui/src/app/utils/subscription-groups/subscription-groups.util.test.ts
https://cortexdata.atlassian.net/browse/TE-1507
Fix test to account for missing field
No UI changes
> test(ui): TE-1507 fix test for missing `notificationSchemes` field

- thirdeye-ui/src/app/rest/alerts/alerts.actions.ts
- thirdeye-ui/src/app/rest/alerts/alerts.interfaces.ts
- thirdeye-ui/src/app/rest/alerts/alerts.rest.test.ts
- thirdeye-ui/src/app/rest/alerts/alerts.rest.ts
https://cortexdata.atlassian.net/browse/TE-1494
Refactoring to make types accurate to wha the api takes in
No UI change
> refactor(ui): TE-1494 use a different interface forget evaluation params

- thirdeye-ui/src/app/components/cohort-detector/dataset-details/dataset-details.component.tsx
- thirdeye-ui/src/app/components/form-basics/input-section/input-section.interfaces.ts
https://cortexdata.atlassian.net/browse/TE-1496
Forcing user to select dimensions when using cohort detector
No UI changes
> fix(ui): TE-1496 do not autoselect all dimensions in cohort detector

- thirdeye-ui/src/app/platform/rest/actions.interfaces.ts
- thirdeye-ui/src/app/rest/actions.interfaces.ts
- thirdeye-ui/src/app/rest/alert-templates/alert-templates.actions.ts
- thirdeye-ui/src/app/rest/alerts/alerts.actions.ts
- thirdeye-ui/src/app/rest/anomalies/anomaly.actions.ts
- thirdeye-ui/src/app/rest/app-analytics/app-analytics.action.ts
- thirdeye-ui/src/app/rest/app-config/app-config.action.ts
- thirdeye-ui/src/app/rest/create-rest-action.test.ts
- thirdeye-ui/src/app/rest/create-rest-action.ts
- thirdeye-ui/src/app/rest/datasets/datasets.actions.ts
- thirdeye-ui/src/app/rest/datasources/datasources.actions.ts
- thirdeye-ui/src/app/rest/enumeration-items/enumeration-items.actions.ts
- thirdeye-ui/src/app/rest/event/event.actions.ts
- thirdeye-ui/src/app/rest/metrics/metrics.actions.ts
- thirdeye-ui/src/app/rest/rca/rca.actions.ts
- thirdeye-ui/src/app/rest/subscription-groups/subscription-groups.actions.ts
- thirdeye-ui/src/app/rest/tasks/tasks.actions.ts
https://cortexdata.atlassian.net/browse/TE-1438
Adding `resetData` to set the internal `data` state to null
No UI changes
> feat(ui): TE-1438 add `resetData` function to all actions

- thirdeye-ui/src/app/components/cohort-detector/dataset-details/dataset-details.component.tsx
- thirdeye-ui/src/app/utils/cohort-detector/cohort-detector.util.ts
https://cortexdata.atlassian.net/browse/TE-1513
Adding convenience functionality to determine good default dates
No UI changes
> feat(ui): TE-1513 use insights api during cohort detection to better default selected dates

- thirdeye-server/src/main/java/ai/startree/thirdeye/PluginLoader.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AccessControlConfiguration.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AccessControlProvider.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/config/ThirdEyeServerConfiguration.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/Plugin.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/accessControl/AccessControlFactory.java
Access control plugin follows the standard plugin format.
https://github.com/startreedata/startree-thirdeye/pull/145
> Fixups for access control plugin

- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AccessControlProvider.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/accessControl/AccessControlFactory.java
> correctly extend the plugin factory interface

- thirdeye-ui/cypress.config.ts
- thirdeye-ui/src/app/components/alert-list-v1/alert-list-v1.component.tsx
- thirdeye-ui/src/app/components/alert-list-v1/alert-list-v1.interfaces.ts
- thirdeye-ui/src/app/components/time-range/time-range-button/time-range-button.component.tsx
- thirdeye-ui/src/app/components/time-range/time-range-selector/date-time-picker-toolbar/date-time-picker-toolbar.component.tsx
- thirdeye-ui/src/app/components/time-range/time-range-selector/time-range-selector-controls/time-range-selector-controls.component.tsx
- thirdeye-ui/src/app/components/time-range/time-range-selector/time-range-selector/time-range-selector.component.tsx
- thirdeye-ui/src/app/components/time-range/time-range-selector/time-range-selector/time-range-selector.interfaces.ts
- thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx
- thirdeye-ui/src/test/e2e/fixtures/anomalies-for-us-store-sales-order.json
- thirdeye-ui/src/test/e2e/support/e2e.ts
- thirdeye-ui/src/test/e2e/support/load-alert-and-anomalies.command.js
- thirdeye-ui/src/test/e2e/support/select-date-range-from-picker.command.js
- thirdeye-ui/src/test/e2e/user-flows/alerts/alerts-all-page.cy.js
- thirdeye-ui/src/test/e2e/user-flows/alerts/alerts-details-flows.cy.js
https://cortexdata.atlassian.net/browse/TE-1481
Cypress tests cases along with changes to the components for easier selection during the tests
> test(ui): TE-1481 alerts all and details page

- thirdeye-ui/src/app/components/alert-wizard-v3/algorithm-selection/algorithm-selection.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/preview-chart.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup.component.tsx
- thirdeye-ui/src/app/components/welcome-landing-page/welcome-step-card/welcome-step-card.component.tsx
- thirdeye-ui/src/app/components/welcome-onboard-datasource/wizard-bottom-bar/wizard-bottom-bar.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasets/onboard-datasets-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasets/onboard-datasets-page.interface.ts
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasource/onboard-datasource-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.component.tsx
- thirdeye-ui/src/app/rest/dto/datasource.interfaces.ts
- thirdeye-ui/src/app/utils/datasources/datasources.util.test.ts
- thirdeye-ui/src/app/utils/datasources/datasources.util.ts
- thirdeye-ui/src/test/e2e/user-flows/welcome-flow.cy.js
https://cortexdata.atlassian.net/browse/TE-1481
Add e2e test cases for welcome flow and medications to existing components for selectivity during tests
> test(ui): TE-1481 welcome flow tests

- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart.interfaces.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/anomalies-filter-panel/filter-configurator/filter-configurator.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/navigate-alert-creation-flows-dropdown/navigate-alert-creation-flows-dropdown.interface.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/navigate-alert-creation-flows-dropdown/navigate-alert-creation-flows-dropdown.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/preview-chart.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/specific-properties-renderer/specific-properties-renderer.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-details/setup-details-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-details/setup-details-page.interface.ts
- thirdeye-ui/src/test/e2e/support/load-alert-and-anomalies.command.js
- thirdeye-ui/src/test/e2e/user-flows/alerts/alerts-create-flows.cy.js
- thirdeye-ui/src/test/e2e/user-flows/alerts/alerts-update-flows.cy.js
https://cortexdata.atlassian.net/browse/TE-1481
Add e2e test cases for alerts create and update flow and modifications to existing components for selectivity during tests
> test(ui): TE-1481 alerts create and update pages

- thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/AnomalyFeedbackMapper.java
- thirdeye-core/src/test/java/ai/startree/thirdeye/mapper/AnomalyFeedbackMapperTest.java
- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AnomalyManagerImpl.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestAnomalyManager.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/AnomalyResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/AnomalyService.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AnomalyFeedbackApi.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/AnomalyFeedbackDTO.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/AnomalyCause.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/AnomalyFeedback.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/AnomalyFeedbackReason.java
https://cortexdata.atlassian.net/browse/TE-1498
Add `created`, `updated`, `updatedBy`, and `reasons` fields for Anomaly Feedback object
> [server] support new payload fields for AnomalyFeedback

- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.component.tsx
- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.interfaces.ts
- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.test.tsx
- thirdeye-ui/src/app/components/anomaly-quick-filters/anomaly-quick-filters.component.tsx
- thirdeye-ui/src/app/components/filter-options-auto-complete/filter-options-auto-complete.component.tsx
- thirdeye-ui/src/app/components/filter-options-auto-complete/filter-options-auto-complete.interfaces.ts
- thirdeye-ui/src/app/components/metrics-report-list/metrics-report-list.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasets/onboard-datasets-page.component.tsx
- thirdeye-ui/src/test/e2e/support/load-alert-and-anomalies.command.js
- thirdeye-ui/src/test/e2e/user-flows/anomalies/anomalies-all-flows.cy.js
https://cortexdata.atlassian.net/browse/TE-1481
e2e tests for anomalies flows
> test(ui): TE-1481 anomalies all flows

- thirdeye-core/src/main/java/ai/startree/thirdeye/detectionpipeline/sql/macro/MacroEngine.java
- thirdeye-core/src/main/java/ai/startree/thirdeye/detectionpipeline/sql/macro/function/TimeGroupFunction.java
- thirdeye-core/src/main/java/ai/startree/thirdeye/detectionpipeline/sql/macro/function/TimeGroupKeyFunction.java
- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/detectionpipeline/sql/macro/MacroEngineTest.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotSqlExpressionBuilder.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datasource/macro/SqlExpressionBuilder.java
- finalize
- add timeGroupKey macro
- add macro to engine
- add target tests
- implement granularityOfTimeFormat in PinotSqlBuilder
> [core] add timeGroupKey macro

- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/components/TimeIndexFiller.java
- clean
- clean
- [detectionpipeline] optimize index filling
> te 1592 improve index filler speed

- .gitignore
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/AlertResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/AlertTemplateResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/AnomalyResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/DataSourceResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/DatasetResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/EnumerationItemResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/EventResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/MetricResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/SubscriptionGroupResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/TaskResource.java
- [mvn] exclude maven-wrapper.jar
- [server] fix content-type in swagger
> te 1666 fix swagger json content type

- thirdeye-core/src/main/java/ai/startree/thirdeye/detectionpipeline/sql/macro/function/TimeGroupKeyFunction.java
- thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/DatasetMapper.java
- thirdeye-core/src/test/java/ai/startree/thirdeye/datalayer/dto/DatasetConfigDTOTest.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotDatasetOnboarder.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/TimeColumnApi.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/DatasetConfigDTO.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/TimeGranularity.java
prep for other changes - refactor time fields
> [spi] remove deprecated nonAdditiveBucketSize

- thirdeye-core/src/main/java/ai/startree/thirdeye/detectionpipeline/sql/macro/function/TimeGroupFunction.java
- thirdeye-core/src/main/java/ai/startree/thirdeye/detectionpipeline/sql/macro/function/TimeGroupKeyFunction.java
- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/detectionpipeline/sql/macro/MacroEngineTest.java
- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/dao/GenericPojoDao.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/util/TimeUtils.java
- [spi] add annotation to TimeUtils
- [core] add support for any time format in precomputed time columns
- [core] refactor TimeGroupKeyFunction
> te 1698 add support for timeformat in precomputed timecolumn bucket

- .github/workflows/publish-backend.yaml
- .github/workflows/publish-frontend.yaml
- refactor publish-backend
- [ci] add publish-frontend workflow
> add ui to publish ci

- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/NamespaceResolver.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/CrudService.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/auth/AuthorizationManagerTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/AlertResourceTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/CrudResourceTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/DataSourceResourceTest.java
https://cortexdata.atlassian.net/browse/TE-1819
> cache namespaces

- thirdeye-core/src/main/java/ai/startree/thirdeye/config/UiConfiguration.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/UiConfigurationApi.java
> [server] Adding intercom to UI Config

- kubernetes/helm/startree-thirdeye/templates/common/internal-certificate.yaml
- kubernetes/helm/startree-thirdeye/templates/coordinator/deployment.yaml
- kubernetes/helm/startree-thirdeye/templates/coordinator/ingress-route-tls.yaml
- kubernetes/helm/startree-thirdeye/templates/scheduler/deployment.yaml
- kubernetes/helm/startree-thirdeye/templates/ui/deployment.yaml
- kubernetes/helm/startree-thirdeye/templates/ui/ingress-route-tls.yaml
- kubernetes/helm/startree-thirdeye/templates/ui/ingress-route-tlsv2.yaml
- kubernetes/helm/startree-thirdeye/templates/ui/servers-transport.yaml
- kubernetes/helm/startree-thirdeye/templates/worker/deployment.yaml
- kubernetes/helm/startree-thirdeye/values.yaml
Added support for TLS v2.0 in the helm chart
> [helm] Support for TLS v2.0

- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertTemplateService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/DataSourceService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/DatasetService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/EnumerationItemService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/EventService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/MetricService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/RcaInvestigationService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/SubscriptionGroupService.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/CrudResourceTest.java
- refactor
- [server] simplify AlertService
- simplify SubscriptionGroupService
> [server] simplify services

- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/EventResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/SubscriptionGroupResource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/CrudService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/EventService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/SubscriptionGroupService.java
- [server] simplify eventService
- simplify SubscriptionGroup service
- refactor
> te 1917 fix soft reset 3

- thirdeye-core/src/main/java/ai/startree/thirdeye/detectionpipeline/sql/macro/MacroEngine.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/components/TimeIndexFiller.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datasource/macro/MacroMetadataKeys.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/util/TimeUtils.java
- add logging to index filler
- add more metadata to query engine
- add more logs to timeIndexFiller
- fix out of bound
> [core] improve logging around time index manipulations

- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
- thirdeye-plugins/thirdeye-postprocessors/src/main/java/ai/startree/thirdeye/plugins/postprocessor/AnomalyMergerPostProcessor.java
- thirdeye-plugins/thirdeye-postprocessors/src/test/java/ai/startree/thirdeye/plugins/postprocessor/AnomalyMergerPostProcessorTest.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/AnomalyDTO.java
- make static what is static
- add shortcircuit in AnomalyDTO equals
- add failing test
> [plugin-postprocessor] separate merging of ignored and non-ignored anomalies

- thirdeye-ui/package-lock.json
- thirdeye-ui/package.json
- thirdeye-ui/webpack.config.dev.js
[TE-2039](https://cortexdata.atlassian.net/browse/TE-2039)
Implement hot-module-replacement for thirdeye-ui using `react-refresh`. 
Reference PR: [Link](https://github.com/startreedata/startree-ui/pull/2144)
https://github.com/startreedata/thirdeye/assets/20799363/90d87233-540f-41a6-95bf-29be5668ee01
> chore(ui): TE-2039 add hot module replacement

- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/NamespaceResolver.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/auth/AuthorizationManagerTest.java
- add failing test
- [server] fix enumerationItem namespace inheritance
> [server] fix enumeration item namespace inheritance

- thirdeye-server/src/test/java/ai/startree/thirdeye/auth/AuthorizationManagerTest.java
rewrite namespace tests
test all cases documented here:
https://dev.startree.ai/docs/get-started-with-thirdeye/access-control-in-thirdeye#namespaces-for-thirdeye-resources
> [server] add namespace tests

- config/server.yaml
- kubernetes/helm/startree-thirdeye/templates/coordinator/configmap.yaml
- kubernetes/helm/startree-thirdeye/templates/scheduler/scheduler-config.yaml
- kubernetes/helm/startree-thirdeye/templates/worker/worker-config.yaml
- kubernetes/helm/startree-thirdeye/values.yaml
- clean
- [k8s] add sentry to helm template
> [k8s] add sentry to helm template

- thirdeye-ui/src/app/rest/dto/subscription-group.interfaces.ts
[TE-2068](https://startree.atlassian.net/browse/TE-2068)
pager-duty → pagerduty for backend compatibility
> fix(ui): TE-2068 pager duty enum fix

- thirdeye-ui/src/app/components/rca/investigation-steps-navigation/investigation-steps-navigation.component.tsx
- thirdeye-ui/src/app/pages/rca/review-share-save-page/review-share-save-page.component.tsx
- thirdeye-ui/src/app/pages/root-cause-analysis-investigation-state-tracker/investigation-state-tracker.component.tsx
- thirdeye-ui/src/app/utils/routes/routes.util.ts
[TE-2051](https://startree.atlassian.net/browse/TE-2051)
- When switching steps with the radio button tabs, the redirect url will be properly updated. Issue being caused by the updated sub url being appended to the existing url instead of replacing.
- Creating a new investigation will redirect the user to the investigation page
> fix(ui): TE-2051 razorpay rca issues

- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/DatabaseService.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/ThirdEyeResultSetDataTable.java
- [pseristence] add debug metrics
- [pinot] clean metrics
> [persistence] add dbReadCallCounter debug metrics

- config/server.yaml
- thirdeye-core/src/main/java/ai/startree/thirdeye/config/TimeConfiguration.java
- thirdeye-notification/src/main/java/ai/startree/thirdeye/notification/AnomalyReportHelper.java
- thirdeye-notification/src/main/java/ai/startree/thirdeye/notification/NotificationReportBuilder.java
- [notification] refactor
- [notification] make notification dateTime format configurable
> [notification] make notification dateTime format configurable

- thirdeye-ui/src/app/components/cohort-detector/dataset-details/dataset-details.component.tsx
- thirdeye-ui/src/app/components/cohort-detector/dataset-details/dataset-details.interfaces.ts
- thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-dimension-groups/setup-dimension-groups-page.component.tsx
[TE-2049](https://startree.atlassian.net/browse/TE-2049)
Append the manually entered query filter value to the alert config
> fix(ui): TE-2049 add custom query filter to the alert config

- thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverRunnable.java
- clean
- clean
- clean
- clean
- clean
- migrate task run metrics
- migrate taskDriverRunnable metrics
> [worker] migrate TaskDriverRunnable to micrometer

- thirdeye-server/src/main/java/ai/startree/thirdeye/ThirdEyeServer.java
- **[server] migrate jetty and jersey metrics to micrometer**
> [server] migrate jetty and jersey metrics to micrometer

- thirdeye-core/src/main/java/ai/startree/thirdeye/datasource/loader/DefaultMinMaxTimeLoader.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/PlanExecutor.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/ThirdEyeServer.java
- thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverThreadPoolManager.java
- **add metrics to executorService**
> [server] migrate jvm metrics to micrometer

- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/util/SqlQueryBuilder.java
- thirdeye-ui/src/app/components/alert-view/tasks-table/tasks-table.component.tsx
- thirdeye-ui/src/app/rest/tasks/tasks.interfaces.ts
- thirdeye-ui/src/app/rest/tasks/tasks.rest.test.ts
- thirdeye-ui/src/app/rest/tasks/tasks.rest.ts
Fix waiting task not displayed in task table in alert page
> fix(ui): TE-2158 fix task table in alert page

- thirdeye-plugins/thirdeye-detectors/src/main/java/ai/startree/thirdeye/plugins/detectors/MeanVarianceRuleDetector.java
- **clean**
- **clean**
- **add suport for DST to mean-variance seasonality case**
- **accept missing data in case of DST**
> [detectors] add support for DST to mean-variance 

- examples/new_customers_holiday/schema.json
- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotSqlExpressionBuilder.java
- **[examples] make one dataset use TIMESTAMP type**
- **[pinot] hotfix timestamp type pinot datetimeconvert issue**
> [pinot] hotfix timestamp type pinot datetimeconvert issue

- thirdeye-ui/src/app/components/copy-button/copy-button.component.tsx
- thirdeye-ui/src/app/components/copy-button/copy-button.interfaces.ts
- thirdeye-ui/src/app/components/rca/heat-map/dimension-search-automcomplete/dimension-search-autocomplete.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/utils/browser/browser.utils.ts
[TE-2112](https://startree.atlassian.net/browse/TE-2112)
- Enable copying the dimension filter (individual and aggregate)
https://github.com/startreedata/thirdeye/assets/20799363/2e2557b2-4390-46b8-a6f6-292f95cb7092
> fix(ui): TE-2112 enable copying the dimension filter

- thirdeye-ui/src/app/rest/dto/datasource.interfaces.ts
- thirdeye-ui/src/app/utils/datasources/datasources.util.test.ts
- thirdeye-ui/src/app/utils/datasources/datasources.util.ts
re-opening
it did not pass the build: 
https://github.com/startreedata/thirdeye/commit/c0e6d36ad924b2fa824eeb64f738f43d3335e3ab/checks
> fix(ui): TE-2175 improve onboarding datasource configuration

- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/TaskManagerImpl.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/NamespaceResolver.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/AnomalyService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/CrudService.java
- **[server] add namespace to created entities**
- **prepare alertService authz**
> [server] add CrudService creates entities with the user namespace 

- thirdeye-ui/src/app/locale/languages/en-us.json
> fix(ui): TE-2112 update text

- thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/AnomalyMapper.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/operator/AnomalyDetectorOperator.java
- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/IntegrationTestUtils.java
- thirdeye-plugins/thirdeye-postprocessors/src/main/java/ai/startree/thirdeye/plugins/postprocessor/AnomalyMergerPostProcessor.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AnomalyApi.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/AnomalyDTO.java
- **[spi] add upper/lower bounds to AnomalyDTO**
- **use Double**
- **add bounds to AnomalyApi**
> [spi] add upper lower bounds to anomalies

- thirdeye-ui/src/app/components/alert-wizard-v3/select-metric/select-metric.utils.ts
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-details/setup-details-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-update-page/alerts-update-json-page.component.tsx
https://startree.atlassian.net/browse/TE-2152
- Show an alert dialogue box while creating / updating an alert if the monitoring granularity is less than 15 minutes
https://github.com/startreedata/thirdeye/assets/67183907/0bf70efe-875e-401d-969d-e09c37ce64db
- Try creating / updating an alert with granularity < 15 minutes
> fix(ui): TE-2152 show confirmation if monitoring granularity less than 15m

- .github/workflows/check-license-header.yml
- .github/workflows/publish-backend.yaml
- .github/workflows/publish-frontend.yaml
- .github/workflows/release.yaml
- .github/workflows/run-backend-tests.yml
GitHub Actions setup-java v3 -> v4
setup-java v3 -> v4
n/a
GitHub actions workflows execute.
> chore(build): setup-java v4

- thirdeye-ui/src/app/components/dataset-create-wizard/dataset-create-wizard.interfaces.ts
- thirdeye-ui/src/app/components/dataset-create-wizard/dataset-properties-form/dataset-properties-form.component.tsx
- thirdeye-ui/src/app/components/dataset-create-wizard/dataset-properties-form/dataset-properties-form.interfaces.ts
- thirdeye-ui/src/app/components/dataset-create-wizard/datasource-verification/datasource-verification.component.tsx
- thirdeye-ui/src/app/components/dataset-create-wizard/datasource-verification/datasource-verification.interfaces.ts
- thirdeye-ui/src/app/components/datasource-list-v1/datasource-list-v1.component.tsx
- thirdeye-ui/src/app/components/datasource-list-v1/datasource-verification/datasource-verification.component.tsx
- thirdeye-ui/src/app/components/datasource-list-v1/datasource-verification/datasource-verification.interfaces.ts
- thirdeye-ui/src/app/pages/datasets-onboard-page/datasets-onboard-page.component.tsx
- thirdeye-ui/src/app/pages/datasources-create-page/datasources-create-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasets/onboard-datasets-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasource/onboard-datasource-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasource/onboard-datasource-page.interfaces.ts
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasource/onboard-datasource-page.utils.ts
- thirdeye-ui/src/app/rest/datasets/datasets.rest.ts
- thirdeye-ui/src/app/rest/datasources/datasources.actions.ts
- thirdeye-ui/src/app/rest/datasources/datasources.interfaces.ts
- thirdeye-ui/src/app/rest/datasources/datasources.rest.test.ts
- thirdeye-ui/src/app/rest/datasources/datasources.rest.ts
- thirdeye-ui/src/app/utils/routes/routes.util.ts
https://startree.atlassian.net/browse/TE-2256
- Fixed the API call signatures to use datasets ID than name
> fix(ui): TE-2256 fix the datasets and datasource api signatures

- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/arch/ArchitectureTest.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/SubscriptionGroupService.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/auth/AuthorizationManagerTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/AlertResourceTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/CrudResourceTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/DataSourceResourceTest.java
- **[server] refactor key object with record**
- **susbcriptionGroupService - add authz check to sendTestMessage**
- **[server] add fixme**
- **add authz to reset**
- **add relatedEntities to subscriptionGroup**
- **add namespace filter to already exist check**
> te 2167 subscription group namespace isolation

- thirdeye-ui/src/app/components/alert-view/tasks-table/tasks-table.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
https://startree.atlassian.net/browse/TE-2026
- Change Column Label in Task Table in Alert Details Page
- Go to Alert details, click on "Options"
- Click on "View task Statuses for Alert"
- Observe column label
> fix(ui): TE-2026 change column label in task table in alert details page

- thirdeye-plugins/thirdeye-postprocessors/src/main/java/ai/startree/thirdeye/plugins/postprocessor/AnomalyMergerPostProcessor.java
- thirdeye-plugins/thirdeye-postprocessors/src/test/java/ai/startree/thirdeye/plugins/postprocessor/AnomalyMergerPostProcessorTest.java
edited spec: 
https://docs.google.com/document/d/1bSbv4XhTQsdGR1XVM_dYL1cK9Q6JlntvzNYmmMiXQRI/edit
> [postprocessor] fix anomaly merger when existing anomaly isIgnore != new anomaly isIgnore

- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotDatasetReader.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/NamespaceResolver.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/AnomalyService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/RcaInvestigationService.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/auth/AuthorizationManagerTest.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/AbstractDTO.java
- **clean**
- **add fixme**
- **[server] remove RcaInvestigation namespace inheritance at read time - set it at write time**
> [server] add namespacing to RcaInvestigation

- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/AnomalyService.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/auth/AuthorizationManagerTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/AlertResourceTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/CrudResourceTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/DataSourceResourceTest.java
- **add todos**
- **[server] add relatedEntities check to authz of RcaInvestigationService**
> [server] add relatedEntities check to authz of RcaInvestigationService

- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertService.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/CrudService.java
- **[server] add related entities read access check to delete**
- **refactorings**
> [server] add related entities check to delete authz and add related entities read authz to crud resource list

- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotThirdEyeDataSource.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/CrudService.java
- thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/ThirdEyeCrudApi.java
- **minor refacto**
- **add cache to anomaly fetch in authorization manager**
> te 2309 add caching to authorization manager

- thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/DaoFilterBuilder.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/DaoFilterUtils.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/CrudService.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/DaoFilterBuilderTest.java
- thirdeye-server/src/test/java/ai/startree/thirdeye/resources/CrudResourceTest.java
- **clean fixme that is done**
- **clean**
- **[server] add namespacing filter to get count and delete**
> [server] add namespacing to GET, DELETE and count in crud resource

- thirdeye-ui/src/app/components/app-bar/app-bar-config-provider/app-bar-config-provider.component.tsx
- thirdeye-ui/src/app/components/app-bar/app-bar-config-provider/app-bar.styles.ts
- thirdeye-ui/src/app/components/app-bar/app-header/app-header.component.tsx
- thirdeye-ui/src/app/components/app-bar/app-header/app-header.inerfaces.ts
- thirdeye-ui/src/app/components/app-bar/app-header/app-header.styles.ts
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/platform/components/auth-provider-v1/auth-provider-v1.component.tsx
- thirdeye-ui/src/app/platform/components/data-grid-v1/data-grid-v1/data-grid-v1.component.tsx
- thirdeye-ui/src/app/platform/stores/auth-v1/auth-v1.interfaces.ts
- thirdeye-ui/src/app/platform/stores/auth-v1/auth-v1.store.ts
- thirdeye-ui/src/app/platform/utils/axios/axios.util.ts
- thirdeye-ui/src/app/rest/dto/workspace.interfaces.ts
- thirdeye-ui/src/app/rest/workspace/workspace-action.ts
- thirdeye-ui/src/app/rest/workspace/workspace.interface.ts
- thirdeye-ui/src/app/rest/workspace/workspace.rest.ts
https://startree.atlassian.net/browse/TE-2386
User can now switch between different workspaces they are part of.
https://github.com/user-attachments/assets/5c2553a2-9674-40f0-a09d-5c6221fc9d4c
> feat(ui): TE-2386 add workspace switcher support on UI

- thirdeye-ui/src/app/components/app-bar/app-header/app-header.component.tsx
> fix(ui): TE-2386 build fix

- thirdeye-ui/src/app/components/app-bar/app-bar-config-provider/app-bar-config-provider.component.tsx
- thirdeye-ui/src/app/utils/user-preferences/user-preferences.interfaces.ts
https://startree.atlassian.net/browse/TE-2424
With multiple workspace, we want the user to land on the same workspace after they refresh the page. 
https://github.com/user-attachments/assets/23361c31-66b0-4dc9-b9c6-b71af03b84c9
> chore(ui): TE-2424 maintain current workspace on refresh

- thirdeye-ui/src/app/platform/stores/auth-v1/auth-v1.store.ts
> fix(ui): TE-2424 avoid persisting workspace in zustand state

- thirdeye-ui/src/app/components/admin-page/recent-failures/recent-failures.component.tsx
- thirdeye-ui/src/app/components/admin-page/recent-failures/task-row/task-row.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/platform/utils/date-time/date-time.util.ts
https://startree.atlassian.net/browse/TE-2372
Show start time and duration(run time) of the tasks in admin tab
> chore(ui): TE-2372 show run time and start time in task table

- thirdeye-ui/src/app/pages/alerts-create-guided-page/tune-alert/tune-alert-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-base-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.styles.ts
- thirdeye-ui/src/app/routers/alerts-guided-create/alerts-guided-create.router.tsx
https://github.com/user-attachments/assets/c16ce360-f385-4317-83e8-25e4e2bd9bc9
> fix(ui): TE-XX fixed create alert issues

- thirdeye-ui/src/app/pages/alerts-all-page-v2/alerts-all-page.component.tsx
- thirdeye-ui/src/app/utils/routes/routes.util.ts
https://startree.atlassian.net/browse/TE-2458
On alert list page, option under create alert button were not redirecting to correct destination. This PR fixes that.
https://github.com/user-attachments/assets/518758ea-f1fe-43bb-aa09-16daf158379d
> fix(ui): TE-2458 handle correct redirect on create alert options

- thirdeye-benchmarks/benchmark_notes.md
- thirdeye-benchmarks/pom.xml
- thirdeye-benchmarks/src/main/java/org/sample/LoadTemplatesBenchmark.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/core/BootstrapResourcesRegistry.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/ResourcesBootstrapService.java
- **[server] add benchmarks for template loading**
- **update notes**
> [server] add benchmark and design notes

- thirdeye-ui/jest.config.js
- thirdeye-ui/jest.setup.js
> chore(ui): TE-2417 fixed breaking tests

- thirdeye-ui/src/app/components/alert-list-v1/alert-list-v1.component.tsx
https://startree.atlassian.net/browse/TE-2473
In alert list page user was not able to scroll within the table. The PR fixes that.
https://github.com/user-attachments/assets/49def493-1b57-4183-8c69-a432c551e7e1
Go to the alert List Page.
Scroll through the alert list.
> fix(ui): TE-2473 fix scroll in aler list

- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasets/onboard-datasets-page.component.tsx
…onboarding
https://startree.atlassian.net/browse/TE-2452
When onboarding a dataset from a datasource, show a better worded message when no dataset is present in the selected source.
> chore(ui): TE-2452 improve message when no dataset is present during onboarding

- thirdeye-ui/src/app/components/impact-dashboard/common/anaylysis-period/analysis-period.styles.ts
- thirdeye-ui/src/app/components/impact-dashboard/detection-performance/line-graph.component.tsx
- thirdeye-ui/src/app/components/impact-dashboard/detection-performance/weekly-graph.component.tsx
- thirdeye-ui/src/app/components/impact-dashboard/investigations/investigations.component.tsx
- thirdeye-ui/src/app/components/impact-dashboard/summary/summary.component.tsx
- thirdeye-ui/src/app/components/impact-dashboard/summary/summary.interfaces.ts
- thirdeye-ui/src/app/components/impact-dashboard/summary/use-summary-data.tsx
- thirdeye-ui/src/app/components/visualizations/bar-graph/bar-graph-internal.component.tsx
- thirdeye-ui/src/app/components/visualizations/time-series-chart/time-series-chart.component.tsx
- thirdeye-ui/src/app/components/visualizations/time-series-chart/time-series-chart.interfaces.ts
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/impact-dashboard-page/data/impact-dashboard-api-requests.interfaces.tsx
- thirdeye-ui/src/app/pages/impact-dashboard-page/data/use-impact-dashboard-api-requests.tsx
- thirdeye-ui/src/app/pages/impact-dashboard-page/impact-dashboard-page.component.tsx
- thirdeye-ui/src/app/platform/components/layout/main/page.styles.ts
- thirdeye-ui/src/app/rest/enumeration-items/enumeration-items.interfaces.ts
- thirdeye-ui/src/app/rest/enumeration-items/enumeration-items.rest.ts
https://startree.atlassian.net/browse/TE-2472
Feedback listed in the above tickets has been addressed
> chore(ui): TE-2472 impact dashboard improvements

- thirdeye-ui/src/app/hooks/useCheckLoadedTemplates.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/alerts-edit-create-common/alerts-simple-advanced-json-container-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.component.tsx
- thirdeye-ui/src/app/rest/alert-templates/alert-templates.actions.ts
- thirdeye-ui/src/app/rest/alert-templates/alert-templates.interfaces.ts
https://startree.atlassian.net/browse/TE-2444
if templates are not loaded in the user’s namespace, make a background api call to load them
> chore(ui): TE-2444 load default alert templates if none present

- thirdeye-server/src/main/java/ai/startree/thirdeye/resources/DataSourceResource.java
[Pinot connection](https://startree.atlassian.net/browse/TE-2441)
This endpoint should be a GET method instead of POST
PR fixes that
Safe to change since this API is not being consumed anywhere
Existing UTs + Integration Tests
Swagger page sanity test -> should return null
> [server] Convert DataSources Recommend endpoint to GET

- thirdeye-ui/src/app/components/home-page/recent-anomalies-v2/recent-anomalies-v2.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/home-page/home-page.component.tsx
https://startree.atlassian.net/browse/TE-2483
https://startree.atlassian.net/browse/TE-2484
https://startree.atlassian.net/browse/TE-2485
https://startree.atlassian.net/browse/TE-2486
- Homepage copy changes requested by Sid
- Go to Homepage
- Check copy for title, top bar startree label, "Deviation" label in Anomalies table header
> fix(ui): TE-2483 fix homepage title copy

- thirdeye-ui/src/app/hooks/useCheckLoadedTemplates.tsx
- thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasource/onboard-datasource-page.component.tsx
- thirdeye-ui/src/app/rest/datasources/datasources.actions.ts
- thirdeye-ui/src/app/rest/datasources/datasources.interfaces.ts
- thirdeye-ui/src/app/rest/datasources/datasources.rest.ts
https://startree.atlassian.net/browse/TE-2442
Auto create the recommended datasource instead of waiting for user to create it.
> fix(ui): TE-2442 auto create recommended datasource

- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotConnectionProvider.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotQueryExecutor.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/restclient/PinotControllerHttpClientProvider.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/restclient/PinotControllerRestClient.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/org/apache/pinot/client/PinotConnectionUtils.java
- **remove DI usage for connection provider**
- **refactorings**
> [pinot] fix potential race condition for controller http client

- kubernetes/helm/startree-thirdeye/templates/coordinator/configmap.yaml
- kubernetes/helm/startree-thirdeye/templates/scheduler/scheduler-config.yaml
- kubernetes/helm/startree-thirdeye/templates/worker/worker-config.yaml
- kubernetes/helm/startree-thirdeye/values.yaml
Testing: 
- PR helm checks
Next steps:
> [helm] add namespace configuration and remove time configuration

- thirdeye-ui/src/app/components/app-bar/app-bar-config-provider/app-bar-config-provider.component.tsx
https://startree.atlassian.net/browse/TE-2492
Show sidebar and app header if auth is disabled
> fix(ui): TE-2492 fix sidebar and app header not showing

- thirdeye-ui/src/app/components/app-bar/app-bar-config-provider/app-bar-config-provider.component.tsx
https://startree.atlassian.net/browse/TE-2492
Removing auth check as its been done in wrapper component
> fix(ui): TE-2492 remove auth check for sidebar and header

- thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx
https://startree.atlassian.net/browse/TE-2493
Show side nav post alert creation via onboarding flow
https://github.com/user-attachments/assets/34ddc012-25b4-4416-abf8-49c44cf6ee08
> fix(ui): TE-2493 show side nav on view alert page

- thirdeye-ui/src/app/pages/home-page/home-page.component.tsx
https://startree.atlassian.net/browse/TE-2494
Point 1 of the above ticket fixed
https://github.com/user-attachments/assets/314394bc-02cd-4050-98a4-53fd0144c334
> fix(ui): TE-2492 redirect loop from home page fixed

- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-base-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.component.tsx
- thirdeye-ui/src/app/utils/constants/constants.util.ts
- thirdeye-ui/src/app/utils/routes/routes.util.ts
https://startree.atlassian.net/browse/TE-2494
Point 2 addressed in the above JRA
https://github.com/user-attachments/assets/a295086e-4d4e-41d3-b85e-fe8485f3ed02
> fix(ui): TE-2492 redirect to home page after first alert creation

- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
- **[server] fix concurrent access to hashmap**
- **manage null key case**
> te 2495 fix concurrent access to hashmap

- thirdeye-ui/src/app/components/alert-add-configuration-modal/alert-add-configration-modal.component.tsx
- thirdeye-ui/src/app/components/alert-add-configuration-modal/alert-add-configration-modal.interfaces.ts
- thirdeye-ui/src/app/components/alert-add-configuration-modal/alert-add-configration-modal.styles.ts
- thirdeye-ui/src/app/components/easy-alert-modal/easy-alert-modal.component.tsx
- thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx
- Added 
https://github.com/user-attachments/assets/ed25d9c7-4354-48df-8c8a-bf575614fac1
> fix(ui): TE-XX added close button to the alert subscription group popup

- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/restclient/PinotControllerRestClient.java
[Prefer mytables endpoint over tables endpoint](https://startree.atlassian.net/browse/TE-2502)
Currently, for fetching all the table names during dataset onboarding flow, `/tables` endpoint is called
This doesn't work properly in shared saas setup, where we have workspace aware tokens instead of master token, and those tokens don't have enough permissions to invoke this method due to RBAC policies
whereas, `/mytables` endpoint works in such setup as it manually checks all the individual tables for RBAC authz
This PR is adding fallback logic to always prefer `/mytables` endpoint over `/tables` endpoint
> [pinot] Prefer mytables endpoint over tables endpoint if available

- thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/DatasetMapper.java
high priority
this is breaking the enterprise TE cohort recommender
see internal discussion
> [core] fix dataset mapper

- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-base-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.styles.ts
https://startree.atlassian.net/browse/TE-2506
In the new simple alert create flow, show the notification configuration step as part of base flow only rather then showing a modal once the alert is created.
> feat(ui): TE-2506 add notification configuration step in new simple create alert flow

- thirdeye-ui/src/app/components/additional-filters-drawer/additional-filters-drawer.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/anomalies-filter-panel/anomalies-filter-panel.interfaces.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/anomalies-filter-panel/anomalies-filter-panel.utils.test.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/anomalies-filter-panel/anomalies-filter-panel.utils.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/specific-properties-renderer/specific-properties-renderer.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx
https://startree.atlassian.net/browse/TE-2508
Simple create alert bug fixes
> fix(ui): TE-2508 create simple alert bug fixes

- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.utils.ts
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx
> fix(ui): TE-XX change default algorithm for simple alerts from mean variance to threshold

- thirdeye-ui/src/app/components/alert-wizard-v3/alert-type-selection/alert-type-selection.interfaces.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/alert-type-selection/alert-type-selection.utils.ts
- thirdeye-ui/src/app/pages/alerts-create-guided-page/alerts-create-guided-page.component.tsx
> fix(ui): TE-XX create alert dx-query-fix

- thirdeye-ui/src/app/components/app-bar/app-bar.component.tsx
- thirdeye-ui/src/app/components/impact-dashboard/common/anaylysis-period/analysis-period.component.tsx
- thirdeye-ui/src/app/components/impact-dashboard/detection-performance/detection-performance.component.tsx
- thirdeye-ui/src/app/components/impact-dashboard/detection-performance/detection-performance.styles.ts
- thirdeye-ui/src/app/components/impact-dashboard/investigations/investigations.component.tsx
- thirdeye-ui/src/app/components/impact-dashboard/summary/summary.component.tsx
- thirdeye-ui/src/app/components/impact-dashboard/summary/use-summary-data.tsx
- thirdeye-ui/src/app/components/impact-dashboard/usage-insights/usage-insights.component.tsx
- thirdeye-ui/src/app/components/visualizations/bar-graph/bar-graph-internal.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/impact-dashboard-page/impact-dashboard-page.component.tsx
- thirdeye-ui/src/app/platform/components/layout/main/page.styles.ts
- thirdeye-ui/src/app/platform/components/nav-bar-v1/nav-bar-link-v1/nav-bar-link-text-v1/nav-bar-link-text-v1.component.tsx
- thirdeye-ui/src/app/platform/components/table/table.component.tsx
- thirdeye-ui/src/app/platform/components/table/table.styles.ts
https://startree.atlassian.net/browse/TE-2501
Bug bash fixes mentioned in the doc here. 
https://docs.google.com/document/d/1OiJJhG0P12SjzNLrjX1TpIydB5TRoGi7quejArTJZXo/edit?tab=t.0#heading=h.nsavgpbe40ov
> fix(ui): TE-2501 impact dashaboard bug bash fixes

- thirdeye-core/src/main/java/ai/startree/thirdeye/datasource/cache/DataSourceCache.java
- thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/operator/SqlExecutionOperator.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotThirdEyeDataSource.java
- thirdeye-plugins/thirdeye-pinot/src/main/java/org/apache/pinot/client/PinotConnectionUtils.java
- thirdeye-scheduler/src/main/java/ai/startree/thirdeye/scheduler/DetectionCronScheduler.java
- thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertService.java
> Enrich exception error logs with exception obj

- thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
[impossible to delete alerts](https://startree.atlassian.net/browse/TE-2554)
Due to related entities check in authorization manager layer, if a dataset is deleted which already has an alert setup on it, every alert related request fails.
This leads to a state where any screen which has to load alerts in some form breaks (even the home page)
and it's impossible to delete the broken alert, either from UI or from swagger APIs
If a related entity has been deleted, then it's not an ideal state but we shouldn't break entire call
This PR fixes the related entities logic by relaxing it in such cases and logs error for further debugging
1. Run local server
2. Delete a dataset, which is already associated to an alert
3. Check home page
4. Check alert page of broken alert
Before: …
> [server] Improve related entities logic in AuthZ Manager

- thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotConnectionUtils.java
Reverts startreedata/thirdeye#1666
will do later - need to validate something else first
> Revert "[pinot] fix ssl config when using https"

- thirdeye-ui/src/app/components/help-drawer-v1/help-drawer-v1.component.tsx
https://startree.atlassian.net/browse/TE-2481
Need help button is hidden till we get it redesigned
> fix(ui): TE-2481 hide need help button

- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.component.tsx
- thirdeye-ui/src/app/components/anomaly-list-v1/anomaly-list-v1.interfaces.ts
- thirdeye-ui/src/app/pages/anomalies-list-page/anomalies-list-page.component.tsx
https://startree.atlassian.net/browse/TE-2556?atlOrigin=eyJpIjoiYmJhYjBkM2FiNjMyNGUzYzk3ZDYzYTJjMzAzYWUzNzUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
Show alert name in the anomalies list page
> fix(ui): TE-2556 show alert name in anomalies list page

- thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-container-page.component.tsx
- thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-information-page.component.tsx
- thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-page.interfaces.ts
https://startree.atlassian.net/browse/TE-2556?atlOrigin=eyJpIjoiYmJhYjBkM2FiNjMyNGUzYzk3ZDYzYTJjMzAzYWUzNzUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
show alert name on anomaly details page
> fix(ui): TE-2556 show alert name on anomaly details page

- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx
> fix(ui): TE-XX fixed query filters for multi dimensional alert

- thirdeye-ui/src/app/components/alert-composite-filters-modal/alert-composite-filters-modal.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup-v3.component.tsx
> fix(ui): TE-XX fixed regression issues in create alert

- thirdeye-ui/src/app/components/additional-filters-drawer/additional-filters-drawer.component.tsx
- thirdeye-ui/src/app/components/additional-filters-drawer/additional-filters-drawer.styles.ts
- thirdeye-ui/src/app/components/alert-json-editor-modal/alert-json-editor-modal.component.tsx
- thirdeye-ui/src/app/components/alert-json-editor-modal/alert-json-editor-modal.interfaces.ts
- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart-v3.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/chart-content-v2/chart-content-v2.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/chart-content-v2/chart-content-v2.interfaces.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/enumeration-items-table/enumeration-items-table.component.tsx
- thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/enumeration-items-table/enumeration-items-table.interfaces.ts
- thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup-v3.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.styles.ts
```
in dx --> sql query, configure notifications appear above the charts instead of below
```
```
let's remove the title here
this may mean the "json editor" will be moved to the row below. (not sure)
goal is to gain some vertical space 
```
```
"json editor" is not a json editor anymore
let's call it "VIEW JSON" for the moment
it may be ok to put it next to "add advanced options" for the moment
let's make sure the behavior is correct when the template is not selected yet. The button can be disabled, or it can show a modal with the config that was used for data preview, whatever is the simplest. 
```
```
in the JSON modal, remove cancel and apply changes. Just put a CLOSE button
```
```
I seem to remember we discussed having a dimension search bar in the dx case.
```
Describe the changes …
> fix(ui): TE-2216 bug fixes for simple alert

- thirdeye-ui/src/app/components/alert-wizard-v3/select-metric/select-metric.utils.ts
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx
https://startree.atlassian.net/browse/TE-2585?atlOrigin=eyJpIjoiNDE4ZmNlZWQyMmY2NDM1MmE0ZTdkZGUyMWI3MWI4ZTIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
Added 10 minutes as an option for granularity in simple alert flow
> feat(ui): TE-2585 add 10 minutes granularity to simple flow

- thirdeye-ui/src/app/components/cron-editor-v1/cron-advance/cron-advance.component.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/properties-form/anomaly-duration-input.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/properties-form/properties-form.component.tsx
- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/properties-form/properties-form.interfaces.ts
- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/properties-form/styles.ts
- thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/subscription-group-details.component.tsx
- thirdeye-ui/src/app/locale/languages/en-us.json
- thirdeye-ui/src/app/rest/dto/subscription-group.interfaces.ts
…groups
https://startree.atlassian.net/browse/TE-2550
Allow user to subscribe to notify anomalies that last more than x days in a row - subscription config
> feat(ui): TE-2550 allow user to add anomaly duration in subscription groups

- thirdeye-ui/src/app/components/impact-dashboard/detection-performance/alert-dropdown.tsx
- thirdeye-ui/src/app/components/impact-dashboard/detection-performance/detection-performance.component.tsx
- thirdeye-ui/src/app/components/impact-dashboard/detection-performance/styles.ts
- thirdeye-ui/src/app/components/impact-dashboard/summary/use-summary-data.tsx
> fix(ui): TE-2544 impact dashbaord feedback

- thirdeye-ui/src/app/components/additional-filters-drawer/additional-filters-drawer.component.tsx
- thirdeye-ui/src/app/components/additional-filters-drawer/additional-filters-drawer.interfaces.ts
- thirdeye-ui/src/app/components/additional-filters-drawer/additional-filters-drawer.styles.ts
- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx
Added Accordion to the input groups in drawer and increase the drawer widthDescribe the changes being introduced to double for better view . 
> fix(ui): Added Accordion to the input groups in drawer and increase the drawer width

- .github/workflows/fe-e2e.yaml
> fix(ui): TE-XX run workflow on push to master

- .github/workflows/fe-e2e.yaml
- thirdeye-ui/e2e/pages/create-alert.ts
- thirdeye-ui/e2e/pages/onboarding.ts
> fix(ui): Added Test fix

- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx
https://startree.atlassian.net/browse/TE-2609
In simple alert flow, user was not able to switch to create subscription group.
> fix(ui): TE-2609 simple alert create subscription group fix

- thirdeye-ui/src/app/components/app-bar/app-header/app-header.component.tsx
- thirdeye-ui/src/app/components/app-bar/app-header/app-header.styles.ts
- thirdeye-ui/src/app/components/app-bar/app-header/workspace.tsx
https://startree.atlassian.net/browse/TE-2610
We were only showing workspace switcher if the there were more than one workspace. With this change we are showing the switcher if the workspace count is more than 0.
> feat(ui): TE-2610 show workspace switcher if workspace count is more than 0

- thirdeye-ui/src/app/components/app-bar/app-header/workspace.tsx
> fix(ui): e2e test fix

- thirdeye-ui/src/app/components/app-bar/app-bar-config-provider/app-bar-config-provider.component.tsx
- thirdeye-ui/src/app/components/create-alert-modal/create-alert-modal.component.tsx
> fix(ui): TE-XXXX quota negative value fix

- thirdeye-ui/src/app/components/create-alert-modal/create-alert-modal.component.tsx
- thirdeye-ui/src/app/pages/subscription-groups-create-page/subscription-groups-create-page.component.tsx
- thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.component.tsx
> fix(ui): TE-XXX quota notif modal fix

- thirdeye-ui/src/app/components/create-alert-modal/create-alert-modal.component.tsx
> fix(ui): TE-XXXX create alert redirect modal persist fix

- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-base-page.component.tsx
> fix(ui): TE-XXXX remove moal after first alert creation

- thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-base-page.component.tsx
> fix(ui): TE-XXXX redirect to alert details after first alert

- thirdeye-persistence/pom.xml
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/aspect/NanoTimeAspect.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/aspect/TimeProvider.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestAnomalyManager.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestAnomalyTaskManager.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestDatasetConfigManager.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestEventManager.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestMetricConfigManager.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestNamespaceConfigurationManager.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/dao/TestGenericPojoDao.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/dao/TestNamespaceConfigurationDao.java
- thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/dao/TestTaskDao.java
- thirdeye-persistence/src/test/resources/META-INF/aop.xml
- **improve test cleanup**
- **[persistence] improve time mock**
- **improve time mock**
> [persistence] improve time mock in tests

- thirdeye-ui/src/app/components/additional-filters-drawer/additional-filters-drawer.component.tsx
> fix(ui): TE-XXXX fix required properties getting reset on applying advanced properties

- thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart.component.tsx
> fix(ui): TE-XXX remove alertId in insight call on edit page && call insight if config changes

- thirdeye-ui/e2e/pages/alert-list.ts
- thirdeye-ui/e2e/tests/anomalies.spec.ts
> fix(ui): TE-XXXX flaky tests fix

- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AbstractManagerImpl.java
- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AnomalyManagerImpl.java
[Investigate and fix anomalies list API slow response](https://startree.atlassian.net/browse/TE-2650)
Follow-up of #1800
This PR moves this change to Abstract Manager so that other entities can also benefit from this 
Optimizes list API for all DTOs
> [persistence] Optimize list API for all entities with combined query

- thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/TaskManagerImpl.java
Fix orphan task cleanup edge case. 
See comment in code and full discussion here: 
https://startreedata.slack.com/archives/C08B4TF4PMJ/p1738867927037999
> [persistence] fix orphan task cleanup in legacy task execution framework

- thirdeye-ui/README.md
> fix(ui): TE-XXXX update readme
