startreedata/thirdeye

thirdeye-ui/webpack.config.prod.js

Add content hash to the file names in production build to bust caching for new deployments

chore(ui): append content hash to production build filenames

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-details/alert-details.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-details/alert-frequency/alert-date-time-cron-advance/alert-date-time-cron-advance.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-properties-builder/alert-template-properties-builder.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.component.tsx
thirdeye-ui/src/app/components/form-basics/input-section/input-section.component.tsx
thirdeye-ui/src/app/components/form-basics/input-section/input-section.interfaces.ts
thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-base-page.component.tsx

Refactoring Alert Wizard to use newly created `InputSection` component which abstracts away the Grid configuration that is commonly used in Edwin's design for all of his form input

refactor(ui): use common grid configuration for form section for alert creation

---

thirdeye-ui/src/app/components/rca/anomaly-time-series-card/anomaly-time-series-card.component.tsx
thirdeye-ui/src/app/components/visualizations/time-series-chart/time-series-chart.component.tsx

fixing bug where changing the zoom would cause the enabled disabled series to reset to default

fix(ui): maintain enabaled and disabled items when zoom changes

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart.component.tsx
thirdeye-ui/src/app/components/anomaly-dimension-analysis/algorithm-table/algorithm-table.utils.tsx
thirdeye-ui/src/app/components/rca/anomaly-time-series-card/anomaly-time-series-card.utils.tsx
thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx
thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-page.component.tsx
thirdeye-ui/src/app/rest/dto/detection.interfaces.ts
thirdeye-ui/src/app/utils/alerts/alerts.util.test.ts
thirdeye-ui/src/app/utils/alerts/alerts.util.ts

With dimension exploration coming, we can no longer assume there will be just one detection result. This PR sets it up so we maintain current feature parity while opening for the possibility of using more than 1

refactor(ui): remove assumption of output_AnomalyDetectorResult_0 key

---

thirdeye-ui/src/app/components/time-range/time-range-button-with-context/time-range-button.component.tsx
thirdeye-ui/src/app/components/time-range/time-range-button-with-context/time-range-button.interfaces.ts
thirdeye-ui/src/app/components/time-range/time-range-button/time-range-button.component.tsx
thirdeye-ui/src/app/components/time-range/time-range-button/time-range-button.interfaces.ts
thirdeye-ui/src/app/components/time-range/time-range-list/time-range-list.component.tsx
thirdeye-ui/src/app/components/time-range/time-range-list/time-range-list.interfaces.ts
thirdeye-ui/src/app/components/time-range/time-range-select/time-range-select.component.tsx
thirdeye-ui/src/app/components/time-range/time-range-select/time-range-select.interfaces.ts
thirdeye-ui/src/app/components/time-range/time-range-selector-popover-content/time-range-selector-popover-content.component.tsx
thirdeye-ui/src/app/components/time-range/time-range-selector-popover-content/time-range-selector-popover-content.interfaces.ts

Support optional min and max dates in the time range selector. Providing a min and max will cause the quick selection list to be filtered for available selections that match the range as well as the selectable dates in the custom date picker

feat(ui): update time selector component to min and max selectable dates

---

kubernetes/helm/startree-thirdeye/templates/coordinator/deployment.yaml
kubernetes/helm/startree-thirdeye/templates/scheduler/deployment.yaml
kubernetes/helm/startree-thirdeye/templates/worker/deployment.yaml

some java options can have commas in their arguments: 
```
-XX:StartFlightRecording=settings=default,delay=3m,disk=true,name=te-run,filename=te-run.jfr,maxsize=500M,maxage=2h
```

[k8s] make helm template javaOpts compatible with commas

---

thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/PlanNodeFactory.java
thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/PostProcessorRegistry.java
thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/operator/PostProcessorOperator.java
thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/plan/PostProcessorPlanNode.java
thirdeye-detectionpipeline/src/test/java/ai/startree/thirdeye/detectionpipeline/PlanExecutorTest.java
thirdeye-detectionpipeline/src/test/java/ai/startree/thirdeye/detectionpipeline/operator/PostProcessorOperatorTest.java
thirdeye-server/src/main/java/ai/startree/thirdeye/PluginLoader.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/Constants.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/Plugin.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/AnomalyDetector.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/postprocessing/AnomalyPostProcessor.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/postprocessing/AnomalyPostProcessorFactory.java

add plugin interfaces and postProcessor operator
Step 2 of anomaly filtering plan
https://docs.google.com/document/d/1YVsTY_c0RFZBKYz757M9aEboYB5kixppgRvqbJmsZ04/edit#heading=h.b01zovq9nib3
WIP: 
Worth checking:  
- namings 
- technique to construct the `<T extends AbstractSpec> spec` for the `PostProcessor` --> simpler than how it's done in DetectorOperator/DetectorRegistry IMO
- registry 
Out of scope: 
- adding a plugin with an implementation
- adding plugin build logic to assembly

[core] add PostProcessor operator

---

scripts/load-datasets.sh
scripts/start-pinot.sh

Pinot v0.9.3 no longers exists in https://downloads.apache.org/pinot/, so let's use 0.11.0.

scripts default to pinot v0.11.0

---

thirdeye-server/src/main/java/ai/startree/thirdeye/alert/DetectionPipelineOutputPostProcessor.java
thirdeye-server/src/test/java/ai/startree/thirdeye/alert/DetectionPipelineOutputPostProcessorTest.java

This is a bugfix where the api returns data beyond the request's start and end date.
The post-processor applies the start and end boundaries, but it would skip timeseries nested within a Combiner result. This fix applies the boundaries to the nested timeseries.
ref: https://cortexdata.atlassian.net/browse/TE-965

PostProcessor correctly processes combiner results

---

thirdeye-server/src/main/java/ai/startree/thirdeye/resources/TaskResource.java

Make /tasks accept startTime and endTime params.
Tested via http requests to `http://localhost:8080/api/tasks?startTime=[gt]1666155900248` and `http://localhost:8080/api/tasks?startTime=[lt]1666155900248`

add startTime and endTime params to /tasks

---

pom.xml
thirdeye-core/pom.xml
thirdeye-core/src/main/java/ai/startree/thirdeye/util/StringTemplateUtils.java
thirdeye-core/src/test/java/ai/startree/thirdeye/util/StringTemplateUtilsTest.java
thirdeye-server/src/main/java/ai/startree/thirdeye/core/ExceptionHandler.java

replace groovy by apache commons text for template variable replacements
fixes an important memory leak described here: 
https://cortexdata.atlassian.net/browse/TE-1038
Risk: 
- some behavior of groovy templating were not unit tested. I tried to add a few tests.
Other options considered:
- update groovy to fix the leak: did not solve the issue - groovy does not expect a runtime to create many templates
- instead of creating a groovy template every time, maintain a hashmap of created groovy templates. Match te templates to groovy templates.
--> means we have to maintain a cache with TTL ourselves. Don't want to do this. Speed is not really an issue here. (pipeline execution time >> template resolution time)
Note on speed: 
I did a very quick benchmark, commons text seems to be faster. …

[core] replace groovy by commons-text for string templating

---

thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/SchedulingTest.java
thirdeye-server/src/main/java/ai/startree/thirdeye/alert/AlertCreater.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/AlertResource.java

fixes alert having lastTimestamp=0, resulting in pressure when the pipeline tries to run from epoch 0.
the strategy of the fix is to enforce the creation of anomalies with a corrected lastTimestamp, not correct it afterwards
also it reduces the surface of potential mistakes, only saveAndOnboard(alertDto) is shared by alert creation and alert reset
In particular, it fixes 2 cases: 
```
- alert save with lastTimestamp=0 
- coordinator crashes before creating the onboarding task
- another worker picks the alert with lastTimestamp=0
```
and 
```
- alert save with lastTimestamp=0 
- onboarding is launched with runtime corrected timestamp
- onboarding fails, lastTimestamp is still zero
- another worker picks the alert with lastTimestamp=0
```
The other solution was to fix the lastTimestamp at …

[server] fix alert plays from epoch zero

---

thirdeye-ui/src/app/platform/components/notification-provider-v1/notification-display-v1/notification-display-v1.component.tsx
thirdeye-ui/src/app/platform/components/notification-provider-v1/notification-display-v1/notification-display-v1.styles.ts

https://cortexdata.atlassian.net/browse/TE-1045
Very long error messages without space in them causes  the displayed alert to go beyond the screen size. Adding a max width and overflow wrap css rules to fix
Before:
After:

fix(ui): TE-1045 ensure alerts stay within screen

---

thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/CrudResource.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/CountApi.java

https://cortexdata.atlassian.net/browse/TE-1048
Endpoint : /api/{entity}/count
Example : `/api/tasks/count?status=FAILED`
Response: 
```
{
"count" : 10
}
```

[server] added count endpoint to CrudResource. Accepts predicates from query params.

---

thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/runner/AnomalyMerger.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/runner/DetectionPipelineTaskRunner.java
thirdeye-worker/src/test/java/ai/startree/thirdeye/worker/task/runner/AnomalyMergerTest.java

prep work to move anomalyMerger downward
separate anomaly merge and anomaly save
anomaly save only belongs to the task run
anomaly merge can be moved downward in a next PR

[worker] separate anomalyMerger from anomaly saving

---

thirdeye-ui/src/app/platform/components/page-v1/page-contents-grid-v1/page-contents-card-v1/page-contents-card-v1.interfaces.ts

[TE-1063](https://cortexdata.atlassian.net/browse/TE-1063)
- Added Material UI's Card component props type definition to `otherProps` since it is passed as de-structured props to the Card component

chore(ui): TE-1063 added missing type definition to otherProps

---

thirdeye-core/src/main/java/ai/startree/thirdeye/alert/AlertTemplateRenderer.java
thirdeye-plugins/thirdeye-bootstrap-open-core/src/main/resources/alert-templates/startree-threshold-percentile.json
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AlertTemplateApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/AlertTemplateDTO.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/template/TemplatePropertyMetadata.java

Add more metadata to template properties.
In alert templates:
Deprecate: 
```json
"defaultProperties": {
"varName": value
}
```
introduce: 
```json 
"properties": [
{
"name": "varName",
"description": "Does this and that [markdown](link)"
"defaultValue": "defaultVal",
"defaultIsNull": false,
"min": ...
"max: ...
"options":  ...
"jsonType": ...
}
],
```
Note:
- breaks the fronted @spham92 because the frontend differentiates default to mandatory variables by looking into `defaultProperties`. Need to also look into propertiesMetadata now
- We can add more fields, like javaType, recommended UI component (eg horizontal range vs numeric input box). Just want to make sure this is compatible with dimension exploration use cases @suvodeep-pyne. In particular, will this make it possible to have a …

te 809 add template property metadata

---

thirdeye-ui/src/app/components/alert-view/enumeration-items-table/enumeration-item-row/enumeration-item-row.component.tsx
thirdeye-ui/src/app/components/alert-view/enumeration-items-table/enumeration-item-row/enumeration-item-row.style.ts
thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx
thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.utils.ts

[TE-1128](https://cortexdata.atlassian.net/browse/TE-1128)
- Added `word-break: break-all` to the name cell in Enumeration Table to prevent overflow ov text
- Created a utils file for alerts view page and moved the constants there

feat(ui): TE-1128 fix overflow for long text in enumeration table

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-properties-builder/alert-template-properties-builder.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-properties-builder/alert-template-properties-builder.interfaces.ts
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.utils.ts
thirdeye-ui/src/app/components/alert-wizard-v2/alert-wizard-v2.styles.ts

[TE-1129](https://cortexdata.atlassian.net/browse/TE-1129)
- Added property description for properties present in the `alert.properties` array

feat(ui): TE-1129 added property description to alert template builder

---

thirdeye-ui/src/app/components/anomaly-dimension-analysis/algorithm-table/algorithm-table.component.tsx
thirdeye-ui/src/app/components/anomaly-dimension-analysis/algorithm-table/algorithm-table.utils.tsx
thirdeye-ui/src/app/components/cohort-detector/cohorts-table/cohorts-table.component.tsx
thirdeye-ui/src/app/components/rca/anomaly-breakdown-comparison-heatmap/anomaly-breakdown-comparison-heatmap.component.tsx
thirdeye-ui/src/app/components/rca/anomaly-time-series-card/anomaly-time-series-card.component.tsx
thirdeye-ui/src/app/components/rca/anomaly-time-series-card/anomaly-time-series-card.utils.tsx
thirdeye-ui/src/app/components/rca/anomaly-time-series-card/rca-chart-legend/filtered-time-series-row/filtered-time-series-row.component.tsx
thirdeye-ui/src/app/locale/languages/en-us.json
thirdeye-ui/src/app/utils/params/params.util.test.ts
thirdeye-ui/src/app/utils/params/params.util.ts

https://cortexdata.atlassian.net/browse/TE-1147
Adding parameter for `concatKeyValueWithEqual` to quote strings or not so it can be used by the new feature that introduced the bug (cohort recommender) and the old code
This is more of a code change than a UI change

fix(ui): TE-1147 fix bug where UI should send non quoted strings

---

thirdeye-ui/src/app/components/alert-list-v1/alert-list-v1.component.tsx

- [TE-1150](https://cortexdata.atlassian.net/browse/TE-1150)
- Turned the alert name text into href

feat(ui): TE-1150 turn alert name into href in alerts table

---

thirdeye-ui/src/app/pages/home-page/home-page.component.tsx

https://cortexdata.atlassian.net/browse/TE-1156
Adding button to allow users the option to view all alerts after creating one from the welcome flow

feat(ui): TE-1156 allow users to navigate to all alerts after successful alert creation from welcome flow

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.utils.ts

timeColumn and timeColumnFormat are inferred automatically now, no need to set them.

chore(ui): TE-1168 update template properties default values

---

thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/AlertResource.java
thirdeye-server/src/test/java/ai/startree/thirdeye/resources/AlertResourceTest.java
thirdeye-server/src/test/java/ai/startree/thirdeye/resources/CrudResourceTest.java
thirdeye-server/src/test/java/ai/startree/thirdeye/resources/DataSourceResourceTest.java

Note: 
- in https://github.com/startreedata/thirdeye/pull/860/files#diff-bb8afb0991edd6ea1a1df622969ccbfec1f23bcb88882f88c888416a144e8af1 the transformation from incomplete DTO to complete DTO is made by the resource
- in https://github.com/startreedata/thirdeye/pull/860/files#diff-9fd90e5ff69e9a40acedb4864d6baa0d480df290cc18ca613f7866a5446bf6a7R89 the transformation from incomplete DTO to complete DTO is made by the authorizationManager 
--> it's not clear yet to me which level should be responsible for this @jacksonargo. I think this will be an important design consideration to avoid bugs.

te 1172 fix access control npe

---

thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup.utils.test.ts
thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup.utils.ts

[TE-1182](https://cortexdata.atlassian.net/browse/TE-1182)
- Removed the generation of `timeColumn` and `timeColumnFormat` from `templateProperties`
[TE-1182]: https://cortexdata.atlassian.net/browse/TE-1182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ui): TE-1182 removed `timeColumn` and `timeColumnFormat` from `templateProperties`

---

thirdeye-server/src/main/java/ai/startree/thirdeye/PluginLoader.java
thirdeye-server/src/main/java/ai/startree/thirdeye/ThirdEyeServerModule.java
thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AccessControlProvider.java
thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
thirdeye-server/src/main/java/ai/startree/thirdeye/config/ThirdEyeServerConfiguration.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/AlertResource.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/CrudResource.java
thirdeye-server/src/test/java/ai/startree/thirdeye/resources/AlertResourceTest.java
thirdeye-server/src/test/java/ai/startree/thirdeye/resources/CrudResourceTest.java
thirdeye-server/src/test/java/ai/startree/thirdeye/resources/DataSourceResourceTest.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/Plugin.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/accessControl/AccessControl.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/accessControl/AccessControlConfiguration.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/accessControl/AccessType.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/accessControl/ResourceIdentifier.java

This pr add a method providing an AccessControl instance to the Plugin interface. 
There's a generic access control config that has a flag for enabled/disabled and a map of plugin specific properties. 
I moved the AccessControl interface and related resources into the spi package so Plugin can reference them.
A single AccessControlProvider class is bound to the AccessControl interface. The Pugin loader can store a new AccessControl instance in the AccessControlProvider, which is subsequently used by server resources. 
I verified that swapping in different access control instances from the plugin loader does work as expected. I also tested w/ https://github.com/startreedata/startree-thirdeye/pull/93 to make sure that the plugin loads and runs correctly.

Add plugin method to set up access control

---

thirdeye-ui/src/app/components/visualizations/time-series-chart/chart-core/chart-core.component.tsx

[TE-1214](https://cortexdata.atlassian.net/browse/TE-1214)
- Fixed the issue where the legend was unable to toggle a data series if a custom renderer was provided for that data series.
- Moved the `enabled = true` filter to the top of the `ChartCore` component so the same filter does not have to be repeated across the component
[TE-1214]: https://cortexdata.atlassian.net/browse/TE-1214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ui): TE-1214 fixed chart legend toggling series for custom render

---

thirdeye-ui/src/app/pages/alerts-update-page/alerts-update-base-page.component.tsx
thirdeye-ui/src/app/pages/anomalies-all-page/anomalies-all-page.component.tsx

https://cortexdata.atlassian.net/browse/TE-1238
No UI changes
Before:
After:

chore(ui): TE-1238 remove duplicated api calls to metrics, datasets, and alerts in all anomalies page

---

thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/specific-properties-renderer/specific-properties-renderer.component.tsx

https://cortexdata.atlassian.net/browse/TE-1228
If sensitivity value exists in the alert template properties, use it as the default value
No UI changes

fix(ui): TE-1228 use existing value for sensitivity if it exists for the slider in new user flow

---

thirdeye-ui/src/app/components/alert-list-v1/alert-list-v1.component.tsx
thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx
thirdeye-ui/src/app/utils/alerts/alerts.util.ts

[TE-1240](https://cortexdata.atlassian.net/browse/TE-1240)
- Alert accuracy uses total anomaly count instead of anomalies with feedback count for denominator
- Added appropriate rounding off to prevent floating point calculation issues
[TE-1240]: https://cortexdata.atlassian.net/browse/TE-1240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ui): TE-1240 using total anomaly count to calculate alert accuracy

---

thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/AlertMapper.java
thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/DataSourceMapper.java
thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/DatasetMapper.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/DataSourceApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/DatasetApi.java

In previous prs, I added the namespace field to the AbstractDTO class and the AlertAPI and AlertTemplateAPI classes. I didn't update the mappers, so the namespace never made it to the database 🤦
Update api<->dto mappers to support namespace field in Alerts, Datasets, Data sources.
Tested by adding namespace field to the resources.

update mappers to support namespace field

---

thirdeye-ui/src/app/platform/utils/number/number.util.test.ts
thirdeye-ui/src/app/platform/utils/number/number.util.ts
thirdeye-ui/src/app/utils/anomalies/anomalies.util.ts

[TE-1207](https://cortexdata.atlassian.net/browse/TE-1207)
- For anomaly deviations that are extremely large (`> 10^5`), the scientific notation is used
- For anomaly deviations that are `<something> / 0`, the label of `Large (Infinite)` is shown instead of `Infinity%` ([link to discussion thread](https://cortexdata.atlassian.net/browse/TE-1207?focusedCommentId=16097)) 
[TE-1207]: https://cortexdata.atlassian.net/browse/TE-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ui): TE-1207 added exponential notation and Infinite label to very large anomaly deviations

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-form-field/alert-template-form-field.component.tsx
thirdeye-ui/src/app/components/parse-markdown/parse-markdown.component.tsx
thirdeye-ui/src/app/platform/components/link-v1/link-v1.interfaces.ts

[TE-1209](https://cortexdata.atlassian.net/browse/TE-1209)
- Implemented `palette.primary.light` color for links in the tooltip markdown
- Improved the code to override markdown components so it can merge with default components
Before:
After:
[TE-1209]: https://cortexdata.atlassian.net/browse/TE-1209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ui): TE-1209 improved contrast on link in markdown tooltip

---

thirdeye-ui/src/app/components/anomaly-quick-filters/anomaly-quick-filter.interface.ts
thirdeye-ui/src/app/components/anomaly-quick-filters/anomaly-quick-filters.component.tsx
thirdeye-ui/src/app/components/entity-cards/anomaly-card/anomaly-card.component.tsx
thirdeye-ui/src/app/components/entity-cards/anomaly-card/anomaly-card.interfaces.ts
thirdeye-ui/src/app/components/entity-cards/root-cause-analysis/anomaly-summary-card/anomaly-summary-card.component.tsx
thirdeye-ui/src/app/components/entity-cards/root-cause-analysis/anomaly-summary-card/anomaly-summary-card.interfaces.ts
thirdeye-ui/src/app/components/metrics-report-list/metrics-report-list.interfaces.ts
thirdeye-ui/src/app/components/metrics-report-list/metrics-report-row/metrics-report-row.component.tsx
thirdeye-ui/src/app/components/rca/anomaly-time-series-card/anomaly-time-series-card.component.tsx
thirdeye-ui/src/app/components/rca/anomaly-time-series-card/anomaly-time-series-card.interfaces.ts
thirdeye-ui/src/app/components/rca/anomaly-time-series-card/anomaly-time-series-card.utils.tsx
thirdeye-ui/src/app/components/visualizations/alert-evaluation-time-series-card/headers/view-anomaly-header.component.tsx
thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-page.component.tsx

https://cortexdata.atlassian.net/browse/TE-1216
Adding support for determining timezone to use from the anomalies details page which now requires fetching the alert details

feat(ui): TE-1216 support timezone in anomalies details page

---

thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/AlertMapper.java
thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/AnomalyMapper.java
thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/ApiBeanMapper.java
thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/AuthorizationConfigurationMapper.java
thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/DataSourceMapper.java
thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/DatasetMapper.java
thirdeye-core/src/test/java/ai/startree/thirdeye/mapper/ApiBeanMapperTest.java
thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AlertApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AlertTemplateApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AnomalyApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AuthorizationConfigurationApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/DataSourceApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/DatasetApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/EnumerationItemApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/AbstractDTO.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/AuthorizationConfigurationDTO.java

This change adds a container AuthorizationConfiguration to store the namespace and any future fields relating to authorization.
Api resources that support AuthorizationConfiguration:
- DataSource
- Dataset
- AlertTemplate
- Alert
- EnumerationItem
- Anomaly

Add AuthorizationConfiguration container for namespace

---

thirdeye-ui/src/app/platform/components/auth-provider-v1/auth-provider-v1.component.tsx

[TE-1284](https://cortexdata.atlassian.net/browse/TE-1284)
Updated auth claims in auth-provider to match platform-ui
- [platform-ui PR](https://github.com/startreedata/startree-ui/pull/1183)
- [Slack Thread](https://cortex-data.slack.com/archives/C04MVHLM8BX/p1675432779815489)
> None
[TE-1284]: https://cortexdata.atlassian.net/browse/TE-1284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ui): TE-1284 added oidc "groups" claim to dex default scopes in platform code in thirdeye-ui

---

thirdeye-ui/src/app/components/rca/anomaly-dimension-analysis/algorithm-table/algorithm-row-expanded.component.tsx
thirdeye-ui/src/app/components/rca/anomaly-dimension-analysis/algorithm-table/algorithm-table.utils.tsx

[TE-1231](https://cortexdata.atlassian.net/browse/TE-1231)
- Baseline offset is being taken into account for the start datetime for alert evaluation data series
- Enabled zoom for the Top Contributors chart to allow better usability since the chart gets zoomed out for large baseline offsets
[TE-1231]: https://cortexdata.atlassian.net/browse/TE-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ui): TE-1231 have the chart timeframe adapt to the baseline offset

---

thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java

Check for read instead of write when evaluating alerts. This way the UI can show the alert graph for anyone who can read the alert.

check for read perm when evalutating alert

---

thirdeye-ui/release.config.js

https://cortexdata.atlassian.net/browse/STUI-611
Slack channel name was hardcoded in release configurations. Going forward, it should be picked up in [CI](https://github.com/startreedata/ci-startree-ui/blob/master/.concourse/tasks/thirdeye-ui/publish.task.yaml#L15) (for example).
Reference: https://github.com/juliuscc/semantic-release-slack-bot#environment-variables
If the approach doesn't work, we'll revert to hardcoded value.

chore(ui): STUI-611 removed hardcoded Slack channel name from release config

---

thirdeye-core/pom.xml
thirdeye-core/src/main/java/ai/startree/thirdeye/alert/AlertDetectionIntervalCalculator.java
thirdeye-core/src/test/java/ai/startree/thirdeye/alert/AlertDetectionIntervalCalculatorTest.java
thirdeye-scheduler/pom.xml
thirdeye-scheduler/src/main/java/ai/startree/thirdeye/scheduler/JobSchedulerService.java
thirdeye-scheduler/src/test/java/ai/startree/thirdeye/scheduler/JobSchedulerServiceTest.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/DatasetApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/AlertDTO.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/DatasetConfigDTO.java

Introduce `mutabilityPeriod` as defined in design doc https://docs.google.com/document/d/1bSbv4XhTQsdGR1XVM_dYL1cK9Q6JlntvzNYmmMiXQRI/edit#heading=h.ffhc3nomfqi9
There are 5 ways a detection pipeline can be triggered: 
- Via the evaluate endpoint
- Via the create endpoint
- Via the reset endpoint
- Via the run endpoint
- Via the cron scheduled execution
`mutabilityPeriod` is only relevant for the cron scheduled execution. It is not applied for other cases. 
Changes: 
- add `mutabilityPeriod` to DatasetConfigDto/Api
- apply `mutabilityPeriod` in the JobSchedulerService
- refactorings to `AlertDetectionIntervalCalculator` and `AlertDetectionIntervalCalculatorTest` - not directly related anymore following rewrite of the PR

[core] add mutabilityPeriod to detectionIntervalCalculator

---

thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/EnumerationItemManagerImpl.java

I think there is a bug in the migration logic that makes enumeration item anomalies messed up when their enumerationItem is migrated.
In the [migrate](https://github.com/startreedata/thirdeye/blob/d5b25e1e14102c53e07139977d849c0a90d510b2/thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/EnumerationItemManagerImpl.java#L119) method:
- `from` is an enumerationItem that has no alertId. So it may have been shared between multiple alerts, meaning some anomalies from different alerts can have this enumeration.
- anomalies are fetched with the filter `enumerationItemId=from.Id`
--> **a filter on the alert Id is missing.**
--> anomalies from multiple alerts are migrated to the enumerationItem
--> I think this happened concurrently between multiple alerts. The last migration …

[persistence] fix anomaly enumerationItem migration logic

---

thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/AlertResource.java

After the alert evaluation is complete, ThirdEye will check access to each result timeseries.
https://cortexdata.atlassian.net/browse/TE-1327
Alert config w/ multiple enum items:
User can only access osx, and that's the only series they see in ui

Check access for enumeration items before returning evaluation results

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-form-field/alert-template-form-field.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-form-field/form-component-for-template-field/form-component-for-template-field.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-form-field/form-component-for-template-field/form-component-for-template-field.interfaces.ts
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-form-field/label-for-template-field/label-for-template-field.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-form-field/label-for-template-field/label-for-template-field.interfaces.ts
thirdeye-ui/src/app/components/json-editor-with-local-cache/json-editor-with-local-cache.component.tsx
thirdeye-ui/src/app/components/json-editor-with-local-cache/json-editor-with-local-cache.interfaces.ts

https://cortexdata.atlassian.net/browse/TE-1142
Refactoring `thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-form-field/alert-template-form-field.component.tsx` to extract out reuseable component pieces
No ui changes

refactor(ui): TE-1142 make form component for template property more reuseable

---

kubernetes/helm/startree-thirdeye/Chart.lock
kubernetes/helm/startree-thirdeye/Chart.yaml
kubernetes/helm/startree-thirdeye/README.md
kubernetes/helm/startree-thirdeye/templates/coordinator/configmap.yaml
kubernetes/helm/startree-thirdeye/templates/scheduler/scheduler-config.yaml
kubernetes/helm/startree-thirdeye/templates/worker/worker-config.yaml
kubernetes/helm/startree-thirdeye/values.yaml

- https://github.com/startreedata/thirdeye/issues/977
- Use `condition` on the MySQL subchart so that local MySQL doesn't have to be deployed
- Add `.Values.mysql.mysqlUrl` so that external URL can be provided
- Updated configmaps so that `mysqlUrl` is used if provided
N/A
From `kubernetes/helm/startree-thirdeye`, I ran the following with different values of `mysql.enabled` and `mysql.mysqlUrl`. Saw working.
```
helm install --dry-run --debug thirdeye . > dry-run.txt
```

[kubernetes] Allow MySQL instance to be external

---

thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AnomalyManagerImpl.java

https://cortexdata.atlassian.net/browse/TE-1344
Introducing new metric to emit anomaly feedback count
metric : `anomalyFeedbackCount `
type : `CachedGauge `
cache timeout : 15 minutes

[persistence] metric to emit anomaly feedback count

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/preview-chart.component.tsx

https://cortexdata.atlassian.net/browse/TE-1356
When passing an entire alert object in evaluation call, time zone is in `alert.template.metadta.timezone`
No UI changes

fix(ui): TE-1356 use evaluation.alert.template in preview charts when for timezone

---

thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/preview-chart.component.tsx

https://cortexdata.atlassian.net/browse/TE-1142
There was a bug where if users navigate away from the filter page during evaluation or insights call in flight, it will navigate users back to the page. This is due to the setSearchParams call. Moved it into a useEffect
No UI changes

fix(ui): TE-1142 fix bug where page would navigate back to filter page

---

thirdeye-ui/src/app/components/cancel-api-calls-on-page-unload/cancel-api-calls-on-page-unload.component.tsx
thirdeye-ui/src/app/components/cancel-api-calls-on-page-unload/cancel-api-calls-on-page-unload.interfaces.ts
thirdeye-ui/src/app/pages/alerts-all-page/alerts-all-page.component.tsx
thirdeye-ui/src/app/rest/alerts/alerts.rest.ts
thirdeye-ui/src/app/rest/create-rest-action.ts
thirdeye-ui/src/app/routers/alert-templates/alert-templates.router.tsx
thirdeye-ui/src/app/routers/alerts-guided-create/alerts-guided-create.router.tsx
thirdeye-ui/src/app/routers/alerts/alerts.router.tsx
thirdeye-ui/src/app/routers/anomalies/anomalies.router.tsx
thirdeye-ui/src/app/routers/app/app.router.tsx
thirdeye-ui/src/app/routers/configuration/configuration.router.tsx
thirdeye-ui/src/app/routers/general-authenticated/general-authenticated.router.tsx

https://cortexdata.atlassian.net/browse/TE-1206
Developers have to explicitly wrap the pages or routers with `CancelAPICallsOnPageUnload` if they wish to cancel API calls on the page or route unload with the react router route definitions.
Some caveats here is that they `key` property is necessary so that the components are unique instance
No UI changes

feat(ui): TE-1206 cancel api calls when user leaves some pages

---

kubernetes/helm/startree-thirdeye/README.md
kubernetes/helm/startree-thirdeye/templates/coordinator/configmap.yaml
kubernetes/helm/startree-thirdeye/templates/scheduler/scheduler-config.yaml
kubernetes/helm/startree-thirdeye/templates/worker/worker-config.yaml
kubernetes/helm/startree-thirdeye/values.yaml

https://cortexdata.atlassian.net/browse/TE-1350
Helm config value renamed from `mysql.mysqlUrl` to `mysql.url`.
Updated the logic in config maps to use the the mysql host name based on `mysql.enabled` flag instead of `mysql.url`

[kubernetes] External mysql connection config refactor

---

thirdeye-ui/src/app/utils/alerts/alerts-configuration-validator.util.test.ts
thirdeye-ui/src/app/utils/alerts/alerts-configuration-validator.util.ts

https://cortexdata.atlassian.net/browse/TE-1366
Allow `${someVariable}` to be a valid value for a template property

fix(ui): TE-1366 allow dimension exploration values in template properties validator

---

thirdeye-ui/src/app/components/visualizations/time-series-chart/time-series-chart.component.tsx
thirdeye-ui/src/app/components/visualizations/time-series-chart/time-series-chart.interfaces.ts

https://cortexdata.atlassian.net/browse/TE-1378
Enabling feature allowing consumers of `TimeSeriesChart` to pass callback function when user makes a range selection.
Usage in the configuration is as follows:
```jsx
{
series,
legend: true,
brush: true,
zoom: true,
tooltip: true,
yAxis: {
position: Orientation.right,
},
chartEvents: {
onRangeSelection: (domain) => {
console.log(domain);
return true;
},
},
}
```
Some fine details about the expected return value of `onRangeSelection`. If return value is falsey (undefined, null, 0, false) then the default zoom behavior will not happen but if the return value is true then the chart will continue to change the zoom window

feat(ui): TE-1378 enable callback function for when users make a range selection in TimeSeriesChart

---

kubernetes/helm/startree-thirdeye/README.md
kubernetes/helm/startree-thirdeye/templates/coordinator/configmap.yaml
kubernetes/helm/startree-thirdeye/templates/scheduler/scheduler-config.yaml
kubernetes/helm/startree-thirdeye/templates/worker/worker-config.yaml
kubernetes/helm/startree-thirdeye/values.yaml

- At my company, we only use PostgreSQL instances so a lot of the infrastructure particularly the security group networking rules are tailored for it
- Right now the default 3306 port is not allowed
- It would be easier for us to allow a different port as opposed to trying to modify the networking rules
- Allow port to be set if external MySQL is provided, default still 3306
Verified working with different values of
```
helm install --dry-run --debug thirdeye . > dry-run.txt
```

[Helm] Enable MySQL port to be set when using external

---

thirdeye-ui/src/app/components/alert-accuracy-colored/alert-accuracy-colored.component.tsx
thirdeye-ui/src/app/components/alert-accuracy-colored/alert-accuracy-colored.interface.ts
thirdeye-ui/src/app/components/alert-list-v1/alert-list-v1.component.tsx
thirdeye-ui/src/app/components/alert-view/enumeration-items-table/enumeration-item-row/enumeration-item-row.component.tsx
thirdeye-ui/src/app/components/alert-view/enumeration-items-table/enumeration-item-row/enumeration-item-row.interfaces.ts
thirdeye-ui/src/app/components/alert-view/enumeration-items-table/enumeration-items-table.component.tsx
thirdeye-ui/src/app/components/alert-view/enumeration-items-table/enumeration-items-table.interfaces.ts
thirdeye-ui/src/app/pages/alerts-all-page/alerts-all-page.component.tsx
thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx
thirdeye-ui/src/app/rest/alerts/alerts.actions.test.ts
thirdeye-ui/src/app/rest/alerts/alerts.actions.ts
thirdeye-ui/src/app/rest/alerts/alerts.interfaces.ts
thirdeye-ui/src/app/rest/alerts/alerts.rest.ts
thirdeye-ui/src/app/rest/dto/ui-alert.interfaces.ts

https://cortexdata.atlassian.net/browse/TE-1418
When you try to check or even click on an alert while accuracy requests are in flight, you can't since the table keeps re-rendering on every request completion. Refactoring to making the accuracy component make the API request so the table does not re-render.
Also removing the accuracy from enumeration item since that just displays the same data as the header.
No visible changes to UI except the removal of the accuracy in enumeration items

refactor(ui): TE-1418 alert accuracy fetches in component

---

thirdeye-ui/src/app/components/page-states/loading-error-state-switch/loading-error-state-switch.component.tsx
thirdeye-ui/src/app/components/page-states/loading-error-state-switch/loading-error-state-switch.interfaces.ts
thirdeye-ui/src/app/pages/alerts-update-page/alerts-edit-base-page.component.tsx
thirdeye-ui/src/app/pages/welcome-page/create-alert/create-alert-page.component.tsx

https://cortexdata.atlassian.net/browse/TE-1449
Sometimes the loading screen takes on entire page width which looks different than when loaded since the loader is not wrapped in `PageContentsGridV1`
Before
After

fix(ui): TE-1449 cosmetic fix to padding on left and right sides with loading switch component

---

.github/workflows/pr.workflow.yaml

https://cortexdata.atlassian.net/browse/STUI-637
Use pull_request_target trigger to allow write permission on fork PRs. pull_request trigger can only grant read permission which makes it impossible for labeler to label a fork PR.

chore(ui): STUI-637 update github workflow

---

thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup.utils.test.ts
thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup.utils.ts

https://cortexdata.atlassian.net/browse/TE-1439
rcaAggregationFunction is optional and should not be always set the same as aggregationFunction. Backend will decide its proper value when it's missing.

fix(ui): TE-1439 make rcaAggregationFunction optional for JSON editor only

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-notifications/alert-notifications.component.tsx

https://cortexdata.atlassian.net/browse/TE-1496
Default the open state on the `initiallySelectedSubscriptionGroups` array length
No UI changes

fix(ui): TE-1496 auto-open notifications if subscription groups are selected

---

examples/AdCampaignData/ingestion_job_spec.yaml
examples/CleanPageViewsData/ingestion_job_spec.yaml
examples/LogisticsData/ingestion_job_spec.yaml
examples/USStoreSalesOrderData/ingestion_job_spec.yaml
examples/new_customers_holiday/ingestion_job_spec.yaml
examples/order_events/ingestion_job_spec.yaml
examples/pageviews/ingestion_job_spec.yaml
examples/pageviews_with_floats/ingestion_job_spec.yaml
examples/pageviews_with_missing_data/ingestion_job_spec.yaml
examples/pageviews_with_nulls/ingestion_job_spec.yaml
examples/us_monthly_air_passengers_simplified/ingestion_job_spec.yaml
scripts/load-datasets.sh
scripts/start-pinot.sh

Pinot version 0.11.0 is not available anymore: https://downloads.apache.org/pinot/
Update the version to 0.12.1 for in quick start scripts.
For the newer version of Pinot, pushJobSpec was missing in original configs and the ingestion always fail when uploading the Segment.
Docs on push job spec:
https://docs.pinot.apache.org/v/release-0.12.1/configuration-reference/job-specification#push-job-spec
Added this spec and loading data into Pinot works again:

[misc] update pinot version from 0.11.0 to 0.12.1

---

pinot-test-container/src/main/java/org/apache/pinot/testcontainer/PinotContainer.java
thirdeye-integration-tests/src/test/resources/datasets/pageviews/batch-job-spec.yml

[TE-1519
](https://cortexdata.atlassian.net/browse/TE-1519)
Pinot version in example has been [upgraded to 0.12.1](https://github.com/startreedata/thirdeye/pull/1068) 
e2e tests are often failed in local due to connection timeout when using 0.11.0 (low performance warnings in Docker Desktop)
Local run with 0.12.1 pinot:

[misc] update e2e test Pinot version from 0.11.0 to 0.12.1

---

kubernetes/helm/startree-thirdeye/templates/coordinator/deployment.yaml
kubernetes/helm/startree-thirdeye/templates/scheduler/deployment.yaml
kubernetes/helm/startree-thirdeye/templates/ui/deployment.yaml
kubernetes/helm/startree-thirdeye/templates/worker/deployment.yaml

initContainers images were not optimal. 
no perf improvement is expected from this change. In effect [images are cached](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy) by default.
goal here is to make it clearer that no java build is happening here.

[k8s] optimize init images

---

thirdeye-plugins/thirdeye-bootstrap-open-core/src/main/java/ai/startree/thirdeye/plugins/bootstrap/opencore/PercentileTemplateCreator.java

Dont need to create percentile templates from the drift templates

[bootstrap] percentile template creator skips drift templates

---

thirdeye-core/src/main/java/ai/startree/thirdeye/alert/AlertDetectionIntervalCalculator.java
thirdeye-core/src/test/java/ai/startree/thirdeye/alert/AlertDetectionIntervalCalculatorTest.java
thirdeye-server/src/main/java/ai/startree/thirdeye/alert/AlertInsightsProvider.java
thirdeye-server/src/test/java/ai/startree/thirdeye/alert/AlertInsightsProviderTest.java

only apply completenessDelay when the endTime is bigger than the data watermark
The change is simple but it’s a big design change: /evaluate and /run are not “pure” anymore --> the behaviour depends on the time at which they run.
These parts were already pretty well tested with unit test and e2e scheduling test so I did not add much tests.

[core] fix completenessDelay behaviour

---

thirdeye-core/src/main/java/ai/startree/thirdeye/config/UiConfiguration.java
thirdeye-core/src/main/java/ai/startree/thirdeye/mapper/UiConfigurationMapper.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/UiResource.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/UiConfigurationApi.java

UI Configuration would look something like this
```
ui:
externalUrl: "http://localhost:8081"
heap:
environmentId: 1234567890
sentry:
clientDsn: https://something.ingest.sentry.io/someid
```
API
```
GET http://localhost:8080/api/ui/config
```
Response
```
{
"authEnabled": false,
"heap": {
"environmentId": "1234567890"
},
"sentry": {
"clientDsn": "https://something.ingest.sentry.io/someid"
}
}
```

[server] Add heap and sentry configs to ui config container

---

pom.xml
thirdeye-server/pom.xml
thirdeye-server/src/main/java/ai/startree/thirdeye/MergingMetricsServlet.java
thirdeye-server/src/main/java/ai/startree/thirdeye/ThirdEyeServer.java
thirdeye-spi/pom.xml
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/PluginClassLoader.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverRunnable.java

Introducing micrometers as a metrics facade (slf4j but for metric collection).
`micrometer-core` does nothing on its own, it's similar to `slf4j-api`.  
We add it to the spi.  
Every modules can now do:
```
counter = Metrics.counter("my_metric")
...
counter.increment()
```
(same with other metrics type)
the `Metrics` static methods makes the creation of metrics possible without DI of the actual registry instance like we do today.
This should make it simpler to add metrics in "deep" places in the code.
Also other libraries used by TE can expose their own metrics.
For prometheus, micrometer automatically respects prom conventions: 
`.` are replaced by `_` , `_total` is appended to counter metrics, default/recommended metrics respect the prometheus convention,  etc...
I suggest we use the …

[spi] add micrometers for simpler metrics collection

---

thirdeye-notification/pom.xml
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/TaskManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/entity/TaskEntity.java
thirdeye-persistence/src/main/resources/db/migration/mysql/V1_196_0__task_add_ref_id.sql
thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestTaskManager.java
thirdeye-scheduler/src/main/java/ai/startree/thirdeye/scheduler/job/DetectionAlertJob.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/bao/TaskManager.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/DetectionPipelineTaskInfo.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/TaskDTO.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/DetectionAlertTaskInfo.java

For a detection pipeline task, it is the alert id. For a notification task, it is the subscription group id

[persistence] Add task.ref_id field to reference an entity connected to a task

---

pom.xml

A regression was introduced in MySql connector.
I opened a ticket here: 
https://bugs.mysql.com/bug.php?id=113378
Ignoring Snyk. There are no security issues in ThirdEye with this downgrade.

[mvn] rollback mysql jdbc client from 8.0.33 to 8.0.28

---

thirdeye-server/src/main/java/ai/startree/thirdeye/auth/NamespaceResolver.java
thirdeye-server/src/test/java/ai/startree/thirdeye/auth/AuthorizationManagerTest.java

- refactor
- add failing test anomaly from enum inherits alert resourceId if enum has no resourceId
- add null annotations - make the bug easier to see
- fix issue
Make the cache a cache of Optional<String> because guava cache cannot return null.
Remove confusing behaviour of chains of optional. Put `.orElse(DEFAULT_NAMESPACE)` in a single place.
Use if else where this can help for debugging.

[server] fix anomaly namespace inherits alert namespace when enum namespace is not set

---

config/server.yaml
pom.xml
thirdeye-server/pom.xml
thirdeye-server/src/main/java/ai/startree/thirdeye/ThirdEyeServer.java
thirdeye-server/src/main/java/ai/startree/thirdeye/config/BackendSentryConfiguration.java
thirdeye-server/src/main/java/ai/startree/thirdeye/config/ThirdEyeServerConfiguration.java

config piece: 
```yaml
sentry:
dsn: "https://dsn.sentry.io"
environment: "production"
tags:
service: coordinator
key: value
```
- `environment` will contain the ui.externalUrl without the forbidden characters
- there will be tags `service` that correspond to the kubernetes labels we use
NEXT:
- helm chart setup will be done in the next PR
- Collection of logs will be done in a second iteration.

[server] add sentry.io collect

---

thirdeye-ui/src/app/components/cohort-detector/cohorts-table/cohorts-table.component.tsx
thirdeye-ui/src/app/components/cohort-detector/cohorts-table/cohorts-table.interfaces.ts
thirdeye-ui/src/app/components/cohort-detector/cohorts-table/cohorts-table.utils.ts
thirdeye-ui/src/app/components/cohort-detector/dataset-details/dataset-details.component.tsx
thirdeye-ui/src/app/components/cohort-detector/dataset-details/dataset-details.interfaces.ts
thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-dimension-groups/setup-dimension-groups-page.component.tsx
thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-base-page.component.tsx
thirdeye-ui/src/app/rest/dto/rca.interfaces.ts
thirdeye-ui/src/app/utils/storage/use-session-storage.ts

[TE-2049](https://startree.atlassian.net/browse/TE-2049)
- Adds a `useSessionStorage` hook.
- Retains the `selectedDimensions` selection on the `Multi-dimension setup` page until the user completes the wizard ...or closes the browser session.
- Also shows the previously selected cohorts
- The entered custom `queryFilter` is also updated and retained.
https://github.com/startreedata/thirdeye/assets/20799363/d2bc18d4-ef33-4922-b196-39661ab8d9ba

fix(ui): TE-2049 retain dimension, query, and selected cohorts when navigating back in alert flow

---

thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-base-page.component.tsx
thirdeye-ui/src/app/routers/alerts-guided-create/alerts-guided-create.router.tsx

[TE-2049](https://startree.atlassian.net/browse/TE-2049)
Fixes the value persistence for state values for the alert creation flow. The values are cleared from session storage when the user enters / leaves the flow, instead of just on creation.
https://github.com/startreedata/thirdeye/assets/20799363/197cd445-ba4c-46a7-a4a8-4870245873fd

fix(ui): TE-2049 ensure the alert creation data does not persist beyond the flow

---

thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/TaskManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/dao/TaskDao.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/util/SqlQueryBuilder.java
thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestAnomalyTaskManager.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/bao/TaskManager.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/detection/health/DetectionTaskStatus.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverRunnable.java
thirdeye-worker/src/test/java/ai/startree/thirdeye/worker/task/HeartbeatTest.java

- **[spi] clean DetectionTaskStatus**
- **always run tasks in order**
- **fetch tasks in order and without concurrency between refs**

[worker] force in-order task execution and prevent concurrent tasks for a same entity 

---

thirdeye-ui/src/app/rest/dto/datasource.interfaces.ts
thirdeye-ui/src/app/utils/datasources/datasources.util.test.ts
thirdeye-ui/src/app/utils/datasources/datasources.util.ts

Add a custom query timeout to the default configuration provided by the frontend.

fix(ui): TE-2175 improve onboarding datasource configuration

---

thirdeye-ui/src/app/components/subscription-group-view/notification-channels-card/notification-channels-card.utils.tsx
thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/recipient-details/groups-editor/groups-editor.component.tsx
thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/recipient-details/groups-editor/slack/slack.component.tsx
thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/recipient-details/groups-editor/slack/slack.interfaces.ts
thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/recipient-details/groups-editor/slack/slack.test.tsx
thirdeye-ui/src/app/locale/languages/en-us.json
thirdeye-ui/src/app/rest/dto/subscription-group.interfaces.ts

[TE-2130](https://startree.atlassian.net/browse/TE-2130)
[UX Mocks](https://www.figma.com/file/9pj4WGZBSNweOeeRKGeSnF/Subscription-groups-%2F-New-feature-%2F-Notification-when-anomaly-is-over?type=design&node-id=612-31389&mode=design&t=iJ9ilvkcHaFldUWB-0)
- Add a checkbox for `Notify when the anomaly period ends` for slack spec in subscription groups
- Show the corresponding value as readonly in spec view

fix(ui): TE-2130 add checkbox to slack edit and view for subscription group spec

---

thirdeye-ui/src/app/components/rca/top-contributors-section/top-contributors-section.component.tsx
thirdeye-ui/src/app/locale/languages/en-us.json
thirdeye-ui/src/app/pages/rca/what-where-page/what-where-page.component.tsx

[TE-2112](https://startree.atlassian.net/browse/TE-2112)
- Add an info message `Scroll down to view heatmap and dimension investigation preview` to the top of the page to help users since the page length is usually large
Video of two rca pages (as detailed below)
https://github.com/startreedata/thirdeye/assets/20799363/3117893c-f374-4744-b7dc-483541d891dc
1. Go to rca page where top contributors has no value ([example link](https://thirdeye.demo.teprod.startree.cloud/root-cause-analysis/v2/anomaly/358371/investigate/what-where-page?startTime=1700697600000&endTime=1703376000000))
> The `Top Contributors` section should collapse when API fetch is resolved
2. Go to rca page where top contributors has valid data to show ([example link](https://thirdeye.demo.teprod.startree.cloud/root-cause-ana …

fix(ui): TE-2112 ux feedback improvements for rca page

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-json/alert-json.component.tsx
thirdeye-ui/src/app/locale/languages/en-us.json

[TE-2076](https://startree.atlassian.net/browse/TE-2076)
Show an error message below the alert json editor if the entered json is invalid.
> The current Alert (create / update) flow, by design, it only captures the last valid state of the JSON. This alert textbox will inform the user of that behavior.
The flow is unaffected, this change just shows an error.

fix(ui): TE-2076 show error for invalid alert json

---

thirdeye-ui/src/app/components/alert-wizard-v3/anomalies-filter-panel/anomalies-filter-panel.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v3/select-metric/select-metric.utils.ts
thirdeye-ui/src/app/components/alert-wizard-v3/threshold-setup/threshold-setup.utils.ts
thirdeye-ui/src/app/utils/constants/constants.util.ts

https://startree.atlassian.net/browse/TE-2134
- Fixed the sensitivity slider values to respect the backend restrictions of `Sensitivity must be in [-26.2, 14.9]`
- Adjust the sensitivity slider on the Filters page to "High" and check if 14.9 is sent as the sensitivity value when reloading the chart

fix(ui): TE-2134 correct sensitivity range in filters page

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-json/alert-json.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-json/alert-json.interfaces.ts
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/preview-chart/preview-chart.interfaces.ts
thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-json-page/alerts-create-json-page.component.tsx
thirdeye-ui/src/app/pages/alerts-update-page/alerts-update-json-page.component.tsx

https://startree.atlassian.net/browse/TE-2076
- If the JSON editor was erroring out on syntax, the Update / Save CTAs should be disabled along with disabling Chart Preview Reload
https://github.com/startreedata/thirdeye/assets/67183907/5942ccbc-11b1-4474-b83a-52583849f8ff
- Try adding / editing an alert and enter invalid JSON
- The "Update" / "Create" CTAs should be disabled along with the Preview Reload button within the chart

fix(ui): TE-2076 improve error messaging in JSON editor

---

thirdeye-ui/src/app/pages/anomalies-all-page/anomalies-all-page.component.tsx
thirdeye-ui/src/app/utils/anomalies/anomalies.util.ts

https://startree.atlassian.net/browse/TE-2212
- For subscription groups with dx alerts that have no `enumerationItem` attached to them, the filtering algorithm on the UI had to be changed
- The algorithm now supports filtering across all types of alerts
- Try filtering through various subscription groups on anomalies list page with subscription to simple and dx alerts with and without `enumerationItem` attached to them

fix(ui): TE-2212 search by subscription group for anomalies bug fix

---

thirdeye-ui/src/app/components/rca/top-contributors-table/preview-chart/preview-chart.component.tsx

https://startree.atlassian.net/browse/TE-2131
Removed redundant API calls, API calls was going twice because of 
1. On filter change useEffect in preview chart was running again.
2. PreviewChart is getting remounted on filter change.
`dimensionCombinations` removed from dependancy array as because of step 2 it will again be remounted with proper props and value of `dimensionCombinations`

fix(ui): TE-2131 fixing duplicate evaluate calls for anomaly heatmap

---

thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx

https://startree.atlassian.net/browse/TE-2236
- Fixed the condition that shows the dimension charts for dx alerts when viewing an alert
- Try viewing multiple DX alerts and check if the dimension charts are visible

fix(ui): TE-2236 fix condition for showing dimension for a dx alert

---

thirdeye-ui/src/app/components/rca/top-contributors-table/top-contributors-row.component.tsx
thirdeye-ui/src/app/components/rca/top-contributors-table/top-contributors-table.component.tsx
thirdeye-ui/src/app/components/rca/top-contributors-table/top-contributors-table.interfaces.ts
thirdeye-ui/src/app/components/rca/top-contributors-table/top-contributors-table.utils.tsx
thirdeye-ui/src/app/locale/languages/en-us.json
thirdeye-ui/src/app/platform/utils/number/number.util.ts

https://startree.atlassian.net/browse/TE-2278
- Added a column for "Change %" to the "Top Contributors" table when investigating an anomaly
- Try toggling the sort for the "Change %" column of the "Top Contributors" section when investigating an anomaly

fix(ui): TE-2278 add a column and sort by percent change in the top contributors table

---

kubernetes/helm/startree-thirdeye/templates/ui/deployment.yaml

This is defined in values.yaml but not being used in the deployment spec

Missing .Values.ui.resources

---

thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/dao/TaskDao.java
thirdeye-scheduler/src/main/java/ai/startree/thirdeye/scheduler/taskcleanup/TaskCleanUpConfiguration.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/Constants.java

- **[scheduler] raise default max number of task delete per run to 5000**
- **[persistence] fix limit not applied correctly in task get method**

[persistence] fix limit not applied correctly in task purge

---

thirdeye-ui/src/app/components/subscription-group-view/notification-channels-card/notification-channels-card.utils.tsx

https://startree.atlassian.net/browse/TE-2334
- Possible fix for a type error on view subscriptions page
- Go to Configuration -> Subscription groups

feat(ui): TE-2334 fix type error on view subscription groups page

---

pom.xml
thirdeye-benchmarks/benchmark_notes.md
thirdeye-benchmarks/pom.xml
thirdeye-benchmarks/src/main/java/org/sample/StringTemplateUtilsBenchmark.java
thirdeye-benchmarks/src/main/resources/alertTemplateDto.json
thirdeye-core/src/main/java/ai/startree/thirdeye/util/StringTemplateUtils.java
thirdeye-core/src/main/java/ai/startree/thirdeye/util/TemplateEngineStringSerializer.java
thirdeye-core/src/main/java/ai/startree/thirdeye/util/TemplateEngineTemplatableSerializer.java
thirdeye-core/src/test/java/ai/startree/thirdeye/util/StringTemplateUtilsTest.java

Before:
```
Benchmark                                  Mode  Cnt     Score    Error  Units
StringTemplateUtilsBenchmark.applyContext  avgt    7  1480.610 ± 56.571  us/op
```
after:
```
Benchmark                                  Mode  Cnt   Score   Error  Units
StringTemplateUtilsBenchmark.applyContext  avgt    7  55.539 ± 0.272  us/op
```

[core] optimize template rendering

---

thirdeye-ui/src/app/components/info-label/info-label.component.tsx
thirdeye-ui/src/app/components/info-label/info-label.interfaces.tsx
thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/properties-form/properties-form.component.tsx
thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/properties-form/properties-form.interfaces.ts
thirdeye-ui/src/app/components/subscription-group-wizard/subscription-group-details/subscription-group-details.component.tsx
thirdeye-ui/src/app/locale/languages/en-us.json
thirdeye-ui/src/app/rest/dto/subscription-group.interfaces.ts

…cription
https://startree.atlassian.net/browse/TE-2363
Added the ability for a user to subscribe to notification for historical anomalies.
https://github.com/startreedata/thirdeye/assets/174305
624/132a709a-b67b-4577-bdbf-6929598dfda0

feat(ui): TE-2363 allow user to opt in to be notified for historical anomalies when creating a subscription

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-properties-builder/alert-template-sectioned-properties/alert-template-sectioned-properties.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-properties-builder/alert-template-sectioned-properties/alert-template-sectioned-properties.interfaces.ts
thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template.utils.ts
thirdeye-ui/src/app/rest/dto/alert-template.interfaces.ts
thirdeye-ui/src/app/utils/alerts/alerts.util.ts

https://startree.atlassian.net/browse/TE-2373
The properties that we display while creating alert in advanced mode are grouped in sections based on their step property.
However as of now, those step names are hardcoded in the UI, and because of which if there is a step that isn't there in that hardcoded list, is getting filtered out and not shown on the UI.
What we are doing with the changes of this PR is that we will be grouping the properties based on their steps dynamically, that way if there is a new category of step introduced, we wont have to make any changes and it will work and show up automatically on the UI grouped together with other properties of the same step.
Attach screenshots of UI/U
https://github.com/user-attachments/assets/1c5c3538-4d3f-49de-937c-e6f216f803a2
X changes, …

fix(ui): TE-2373 display all properties while creating alert in advanced mode

---

pom.xml

[SECURITY - upgrade jackson to latest version](https://startree.atlassian.net/browse/TE-2383)
Upgrading Jackson to the latest version to fix [DoS vulnerability](https://github.com/startreedata/thirdeye/pull/1504)

[mvn] Upgrade jackson to latest version

---

thirdeye-plugins/thirdeye-bootstrap-open-core/src/main/resources/alert-templates/startree-absolute-rule.json
thirdeye-plugins/thirdeye-bootstrap-open-core/src/main/resources/alert-templates/startree-mean-variance.json
thirdeye-plugins/thirdeye-bootstrap-open-core/src/main/resources/alert-templates/startree-percentage-rule.json
thirdeye-plugins/thirdeye-bootstrap-open-core/src/main/resources/alert-templates/startree-threshold.json
thirdeye-server/src/main/java/ai/startree/thirdeye/rca/RcaInfoFetcher.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AlertMetadataApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/AlertMetadataDTO.java

https://startree.atlassian.net/browse/TE-2382
Aggregation function for RCA heatmap is resolved by following logic currently:
1. If custom RCA aggregation fn is provided, use it
2. if metric does not exists, default to COUNT 
3. else, use default aggregation fn of the metric
In cases 2 and 3, alert aggregation function should be used for RCA heatmap if custom rca aggregation fn is not present in template properties
This PR introduces changes to include a new metadata property in alert template - detectionAggregationFunction, which will be set to the alert aggregation function. It is being used to decide aggregation fn for rca heatmap if custom rca aggregation fn is not provided
Scenario: An alert which is based on MAX aggregation function, but the metric's default aggregation fn is SUM …

[server] Fix rca heatmap aggregation fn logic

---

thirdeye-plugins/thirdeye-notification-email/src/main/java/ai/startree/thirdeye/plugins/notification/email/EmailSendgridNotificationService.java
thirdeye-plugins/thirdeye-notification-email/src/main/java/ai/startree/thirdeye/plugins/notification/email/EmailSmtpNotificationService.java

https://startree.atlassian.net/browse/TE-2197
0 anomalies emails are being sent in few cases. This happens when have 0 anomalies and non-zero completed anomalies.
In [[worker] Feat: Completed Anomalies. Adding filtering logic stub for getting completed anomalies.](https://github.com/startreedata/thirdeye/commit/00b3e83bb256459b5e3933c2944d51db9a3335de#diff-8cf81be035b197f50b6eb9c91f626782d8dfd128424f49db76a2e7333c624bb7), concept of completed anomalies was introduced to the NotificationTaskRunner
Along with computing anomalies to be reported, we started computing completed anomalies that may be reported in addition. The preliminary check to decide whether notification should be dispatched or not, was changed to check for both anomalies and completed anomalies. 
Hence, if either of …

[notification] Add zero anomalies check for notifications

---

thirdeye-ui/src/app/components/admin-page/recent-failures/recent-failures.component.tsx
thirdeye-ui/src/app/components/alert-view/alert-chart/alert-chart.component.tsx
thirdeye-ui/src/app/components/alert-view/enumeration-items-table/enumeration-item-row/enumeration-item-row.component.tsx
thirdeye-ui/src/app/components/alert-view/sub-header/alert-sub-header.component.tsx
thirdeye-ui/src/app/components/alert-view/subscription-groups-table/subscription-groups-table.component.tsx
thirdeye-ui/src/app/components/alert-view/tasks-table/tasks-table.component.tsx
thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/enumeration-items-table/enumeration-item-row/enumeration-item-row.component.tsx
thirdeye-ui/src/app/components/app-bar/app-header/app-header.styles.ts
thirdeye-ui/src/app/components/home-page/recent-anomalies-v2/recent-anomalies-v2.component.tsx
thirdeye-ui/src/app/components/home-page/recent-anomalies/recent-anomalies.component.tsx
thirdeye-ui/src/app/components/third-party-lib-setup-providers/analytics-and-error-reporting-provider-v1/analytics-and-error-reporting-provider-v1.component.tsx
thirdeye-ui/src/app/pages/alerts-all-page/alerts-all-page.component.tsx
thirdeye-ui/src/app/pages/alerts-create-guided-page/setup-metric/setup-metric-page.component.tsx
thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx
thirdeye-ui/src/app/pages/anomalies-create-page/anomalies-create-page.component.tsx
thirdeye-ui/src/app/pages/home-page/home-page.component.tsx
thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.component.tsx
thirdeye-ui/src/app/rest/alerts/alerts.actions.ts
thirdeye-ui/src/app/rest/alerts/alerts.interfaces.ts
thirdeye-ui/src/app/rest/alerts/alerts.rest.ts
thirdeye-ui/src/app/rest/dto/alert.interfaces.ts
thirdeye-ui/src/app/rest/hooks/fetch-query.interfaces.ts
thirdeye-ui/src/app/rest/hooks/useFetchQuery.tsx

… in workspace
https://startree.atlassian.net/browse/TE-2389
With the workspace switcher header, we have to make sure its sticky and content behind it, while scrolling the page is not visible.
This PR also fixes an issue where we want to redirect the user to home page from the welcome landing page, if the workspace they are in, already has alerts
https://github.com/user-attachments/assets/2e0be10e-7a72-4cee-98de-eefc847d6182

fix(ui): TE-2389 zIndex fix and redirect to home page if alerts exist in workspace

---

thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/enumeration-items-table/enumeration-item-row/enumeration-item-row.component.tsx

… alert
https://startree.atlassian.net/browse/TE-2411
When updating an alert which has enumeration items, we do not have to pass the alertId to the evaluate call 
https://github.com/user-attachments/assets/25c002b5-6eff-422c-89da-ddb0d98559b7
1. Go to any alert which has enumeration items.
2. Open the edit alert page.
3. Update any alert property.
4. Click on Load chart preview.
5. See in the evaluate api call in network tab that alertId is not being passed in the payload

fix(ui): TE-2411 avoid passing alertId in evaluate call when updating alert

---

thirdeye-ui/src/app/components/alert-wizard-v3/preview-chart/chart-content/chart-content.component.tsx

https://startree.atlassian.net/browse/TE-2418
When creating multi dimensional alert, preview chart was not loading if there is only one enumeration item. This PR fixes that
https://github.com/user-attachments/assets/ba010bb3-c4a5-4953-86d3-1e2755efee82
1. Go to create multi dimensional alert.
2. Add one enumeration item only.
3. Click on load chart.
4. See that that alert chart loads.

fix(ui): TE-2418 fix preview load alert with single enum item

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-notifications/subscription-groups/subscription-groups.component.tsx

https://startree.atlassian.net/browse/TE-2426
User was not able to scroll through subscription groups in the create alert flow, which has been fixed via this PR
https://github.com/user-attachments/assets/9e0dfff6-fc1f-40be-8b04-e254ca41c2fb

fix(ui): TE-2426 fix scroll in subscription group in create alert flow

---

thirdeye-ui/src/app/components/alert-list-v1/alert-list-v1.component.tsx
thirdeye-ui/src/app/components/alert-template-list-v1/alert-template-list-v1.component.tsx
thirdeye-ui/src/app/components/anomalies-view/feedback-card/feedback-card.interfaces.ts
thirdeye-ui/src/app/components/event-list-v1/event-list-v1.component.tsx
thirdeye-ui/src/app/components/metric-list-v1/metric-list-v1.component.tsx
thirdeye-ui/src/app/pages/alerts-anomalies-page/alerts-anomalies-page.component.tsx
thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-information-page.component.tsx
thirdeye-ui/src/app/platform/components/data-grid-v1/data-grid-v1/data-grid-v1.component.tsx

… type
https://startree.atlassian.net/browse/TE-2143
If the anomaly has any investigations, show them on the anomaly details page irrespective of there is feedback or not

chore(ui): TE-2143 show saved investigations irrespective of feedback type

---

kubernetes/helm/startree-thirdeye/templates/coordinator/configmap.yaml
kubernetes/helm/startree-thirdeye/templates/scheduler/scheduler-config.yaml
kubernetes/helm/startree-thirdeye/templates/worker/worker-config.yaml
kubernetes/helm/startree-thirdeye/values.yaml

[AccessControl Helm Changes](https://startree.atlassian.net/browse/TE-2438)
Adding accessControl to helm template server yaml configuration
It is used to enable/disable the ThirdEyeAuthorizer Plugin (disabled by default)
Validate helm install locally
`cd kubernetes/helm/startree-thirdeye`
`helm install --generate-name . --debug --dry-run`
[helm-debug-output.log](https://github.com/user-attachments/files/17024047/helm-debug-output.log)

[k8s] add accessControl to helm template

---

thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertService.java
thirdeye-server/src/test/java/ai/startree/thirdeye/resources/AlertResourceTest.java

[RCA entities in inconsistent state in db when an alert is deleted](https://startree.atlassian.net/browse/TE-2440)
When an alert is deleted, [associated entities are deleted](https://github.com/startreedata/thirdeye/blob/d8affb568fd3e8c7977be4208a9be6151591197b/thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertService.java#L110): anomalies, enumeration items
But associated RCA Investigations are not deleted
This later causes issues because RCA investigation are parentless and breaks few APIs of RCA investigation
This PR introduces logic to delete associated RCAInvestigations in Alert delete flow
Tested locally by spawning service+UI and simulating delete alert flow
1. Create a RCA investigation corresponding to an anomaly
2. Delete associated alert of that anomaly
3. Verify …

[server] Delete associated RCAInvestigations in Alert Delete Flow

---

kubernetes/helm/startree-thirdeye/templates/coordinator/configmap.yaml
kubernetes/helm/startree-thirdeye/templates/scheduler/scheduler-config.yaml
kubernetes/helm/startree-thirdeye/values.yaml

[Change TE Helm Template to allow disabling Calendar Events](https://startree.atlassian.net/browse/TE-2457)
There are few cases where we would want to disable calendar events explicitly for a certain environment
currently, there's no way to pass empty calendars list
Hence adding new flag to allow disabling calendar events
By default, it will be set to true in values.yaml, exhibiting the current behaviour
One can pass config.loadCalendarEvents as false in chart values to disable holiday events loading
Ran helm install locally and compared changes before and after the PR
No explicit chart value passed
`helm install startree-thirdeye startree-thirdeye --dry-run`
Before:
[before.txt](https://github.com/user-attachments/files/17129341/before.txt)
After: …

[helm] Add flag to toggle holiday calendar events

---

thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertService.java

[RCA entities in inconsistent state in db when an alert is deleted](https://startree.atlassian.net/browse/TE-2440)
When an alert is reset, [associated anomalies are deleted](https://github.com/startreedata/thirdeye/blob/d8affb568fd3e8c7977be4208a9be6151591197b/thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertService.java#L303)
but rca investigations corresponding to those anomalies are not deleted
This later causes issues because RCA investigation are parentless and breaks few APIs of RCA investigation
This PR introduces logic to delete associated RCAInvestigations in Alert reset flow
Tested locally by spawning service+UI and simulating reset alert flow
1. Create RCA investigation(s) corresponding to anomalies of a specific alert from UI
2. Reset anomalies of that alert, …

[server] Delete associated RCAInvestigations in Alert Reset Flow

---

thirdeye-plugins/thirdeye-oauth/pom.xml
thirdeye-plugins/thirdeye-oauth/src/main/java/ai/startree/thirdeye/plugins/oauth/ThirdEyeOAuthThirdEyeAuthenticator.java
thirdeye-plugins/thirdeye-oauth/src/test/java/ai/startree/thirdeye/plugins/oauth/ThirdEyeOAuthAuthenticatorTest.java

fix the oauth authenticator throwing an NPE when the authorization token is not passed
the NPE is caught and this generates an ERROR level log that is reported in sentry

[oauth] fix oauth authenticator logging NPE

---

thirdeye-ui/src/app/components/alert-view/alert-options-button/alert-options-button.component.tsx
thirdeye-ui/src/app/locale/languages/en-us.json

https://startree.atlassian.net/browse/TE-2461
In rerun anomaly detection, the endTime was being sent incorrectly as defaultStartTime. Fixed it to use datasetEndTime

fix(ui): TE-2461 send datasetEndTime in rerun anomaly detection

---

thirdeye-ui/package-lock.json
thirdeye-ui/package.json

https://startree.atlassian.net/browse/TE-2414
Upgrade axios version to fix snyk vulnerability

chore(ui): TE-2414 upgrade axios version

---

thirdeye-ui/src/app/pages/swagger/index.tsx

before: opened by default
after: closed by default
would like to get this merged before sharing a new version with on-premise customers

fix(ui): TE-2471 close sections in swagger ui by default

---

thirdeye-server/src/main/java/ai/startree/thirdeye/auth/ThirdEyeAuthorizerProvider.java
thirdeye-server/src/test/java/ai/startree/thirdeye/resources/testutils/SingleNamespaceAuthorizer.java
thirdeye-server/src/test/java/ai/startree/thirdeye/resources/testutils/SingleResourceAuthorizer.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/auth/ThirdEyeAuthorizer.java

[Pinot connection](https://startree.atlassian.net/browse/TE-2441)
Adding generateDatasourceConnection method to ThirdEyeAuthorizer interface
The purpose of this method is to provide placeholder to implement one's own custom datasource connection
One can override the default implementation by using/implementing ThirdEyeAuthorizerPlugin
This method is not being used anywhere currently
It will be integrated into Authorization Manager in upcoming PR to be exposed as a new API
Existing Tests and CI

[spi] Add generateDatasourceConnection to ThirdEyeAuthorizer interface

---

thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/DataSourceResource.java
thirdeye-server/src/main/java/ai/startree/thirdeye/service/DataSourceService.java
thirdeye-server/src/test/java/ai/startree/thirdeye/resources/DataSourceResourceTest.java

[Pinot connection](https://startree.atlassian.net/browse/TE-2441)
Adding new API `api/data-sources/recommend`
It will be used in datasource onboarding UI flow to generate recommended datasource connection config 
(importantly for Shared SaaS setup)
Depends on https://github.com/startreedata/thirdeye/pull/1584
UTs and
Sanity swagger test (should return 200 response with null body due to default implementation)

[server] Add recommend API to datasource resource

---

thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/auth/ThirdEyeAuthorizer.java

[Pinot connection](https://startree.atlassian.net/browse/TE-2441)
Adding default implementation of generateDatasourceConnection method to avoid breaking change
Existing Tests and CI

[spi] Add default implementation of generateDatasourceConnection in ThirdEyeAuthorizer

---

thirdeye-ui/src/app/components/alert-wizard-v2/alert-template/alert-template-properties-builder/alert-template-sectioned-properties/alert-template-sectioned-properties.component.tsx

https://startree.atlassian.net/browse/TE-2474
In advance mode of alert creation, all properties of template were not showing. This was due to a bug in how we were filtering to show the properties in different sections. This PR fixes that
https://github.com/user-attachments/assets/2ee6cd2c-c976-424e-829b-a4bde3daad86

fix(ui): TE-2474 show all template properties in advance create mode

---

thirdeye-ui/src/app/locale/languages/en-us.json
thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasource/onboard-datasource-page.component.tsx
thirdeye-ui/src/app/rest/datasources/datasources.actions.ts
thirdeye-ui/src/app/rest/datasources/datasources.interfaces.ts
thirdeye-ui/src/app/rest/datasources/datasources.rest.ts

https://startree.atlassian.net/browse/TE-2442
In the welcome onboarding flow, if user doesn;t have any datasource configured, we will show them the ecommnded datasources which are returned via /api/data-sources/recommend endpoint

feat(ui): TE-2442 show recommended datasources during onboarding

---

config/server.yaml
thirdeye-benchmarks/src/main/java/org/sample/LoadTemplatesBenchmark.java
thirdeye-core/src/main/java/ai/startree/thirdeye/ThirdEyeCoreModule.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/NamespaceConfigurationManagerImpl.java
thirdeye-plugins/thirdeye-bootstrap-open-core/src/main/java/ai/startree/thirdeye/plugins/bootstrap/opencore/OpenCoreBoostrapResourcesProvider.java
thirdeye-plugins/thirdeye-bootstrap-open-core/src/test/java/ai/startree/thirdeye/plugins/boostrap/opencore/OpenCoreBoostrapResourcesProviderTest.java
thirdeye-server/src/main/java/ai/startree/thirdeye/ThirdEyeServerModule.java
thirdeye-server/src/main/java/ai/startree/thirdeye/config/ThirdEyeServerConfiguration.java
thirdeye-server/src/main/java/ai/startree/thirdeye/core/BootstrapResourcesRegistry.java
thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertTemplateService.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/NamespaceConfigurationApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/TemplateConfigurationApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/NamespaceConfigurationDTO.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/TemplateConfigurationDTO.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/TimeConfigurationDTO.java

Issue:
https://startree.atlassian.net/browse/TE-2491
Description:
This PR adds support for:
- a default workspace configuration - it is exposed in the server config file
- `time` configuration is now deprecated. It still has precedence over the workspace configuration for the moment
- TemplateConfiguration in the NamespaceConfiguration. It allows some control on how templates are generated.   
- queryLimit control in TemplateConfiguration. The default query limit of templates can be set as a configuration. This is to be compatible with StarTree Cloud free tier.
Testing:
- unit tests 
- manual local test (Cyril)
Not part of the PR:
- kubernetes helm chart update
- enterprise query limit logic

[bootstrap] add template configuration to namespace configuration

---

thirdeye-ui/src/app/pages/welcome-page/landing/landing-page.component.tsx

https://startree.atlassian.net/browse/TE-2493
Onboarding flow should use new alert flow ux as default
https://github.com/user-attachments/assets/fd71c79d-b320-45fc-9b04-a348bd3f6c71

fix(ui): TE-2493 use new alert flow from onboarding page

---

thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java

**Issue:** 
There can be concurrent modifications of the cache maps used in the AuthorizationManager.
**Fix:** 
Use ConcurrentMaps

[server] fix concurrent access to hashmap

---

thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/restclient/PinotControllerRestClient.java

This log was noisy in prod because it happens every time the healthcheck is performed. 
See https://startree.atlassian.net/browse/TE-2504

[pinot] remove noisy log

---

pom.xml

[upgrade dropwizard to 3.0.10](https://startree.atlassian.net/browse/TE-2525)
Upgrading dropwizard version to [latest 3.0.X version](https://mvnrepository.com/artifact/io.dropwizard/dropwizard-core) 
```diff
diff dependency-tree-before dependency-tree-after 
1d0
< ./mvnw dependency:tree
87,89c86,88
< [INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.17.2:compile
< [INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.17.2:compile
< [INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.17.2:compile
---
> [INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.18.1:compile
> [INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.18.1:compile
> [INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.18.1:compile
95c94
< [INFO] \- …
```

[mvn] bump dropwizard version to 3.0.10

---

thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/notification/NotificationTaskFilterIntegrationTest.java
thirdeye-notification/src/main/java/ai/startree/thirdeye/notification/NotificationTaskFilter.java
thirdeye-notification/src/main/java/ai/startree/thirdeye/notification/NotificationTaskPostProcessor.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/SubscriptionGroupApi.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/dto/SubscriptionGroupDTO.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/runner/NotificationTaskRunner.java

**Issue:** 
https://startree.atlassian.net/browse/TE-2342 
**Description:**
This PR adds support for a new parameter `minimumAnomalyLength` in the SubscriptionGroup configuration. 
Only anomalies of length >= minimumAnomalyLength are notified.
**Testing:**

[notification] add anomaly minimum length filter

---

thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/restclient/PinotControllerRestClient.java

Error log when fetching schema from pinot controller currently doesn't log exception object
This PR adds exception obj to the log

[thirdeye-pinot] Enrich pinot controller schema fetch error log

---

pom.xml
thirdeye-plugins/thirdeye-pinot/pom.xml

The JDBC pinot connection was never used, then deprecated, then removed. 
This PR totally removes the dependency to make it simpler to upgrade the Pinot version.

[pinot] remove unused jdbc connector

---

config/server.yaml
thirdeye-integration-tests/src/test/resources/anomalyresolution/config/server.yaml
thirdeye-integration-tests/src/test/resources/happypath/config/server.yaml
thirdeye-integration-tests/src/test/resources/scheduling/config/server.yaml
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/TaskManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/dao/TaskDao.java
thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestAnomalyTaskManager.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/bao/TaskManager.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverConfiguration.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverRunnable.java
thirdeye-worker/src/test/java/ai/startree/thirdeye/worker/task/HeartbeatTest.java

Problem: 
The current task acquisition logic uses an optimistic lock. Read  https://en.wikipedia.org/wiki/Optimistic_concurrency_control if necessary. 
Tasks are picked **in order** by every worker.
In order was not enforced before, so there was less chance of contention.
In order is now enforced, so contention is more likely to happen.
At around 5 workers (~4 threads?), workers are very likely to select the same task and spend most of their time rolling back instead of acquiring the task and making progress. 
This PR implements a pessimistic lock, and uses the SKIP LOCKED statement to avoid lock contention.
This should be roughly as fast under small load / small number of workers, and this should scale better with high number of workers (>5).
Realistic benchmarks will be necessary and …

[worker] add pessimistic lock task acquisition

---

thirdeye-notification/src/main/java/ai/startree/thirdeye/notification/NotificationDispatcher.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/InternalResource.java
thirdeye-server/src/main/java/ai/startree/thirdeye/service/InternalService.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/util/MetricsUtils.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverRunnable.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskRunner.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/runner/DetectionPipelineTaskRunner.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/runner/NotificationTaskRunner.java
thirdeye-worker/src/test/java/ai/startree/thirdeye/worker/task/HeartbeatTest.java

[Metrics - per namespace](https://startree.atlassian.net/browse/TE-2454)
This PR adds add a namespace tag to all metrics where relevant
1. Run local thirdeye server and UI
2. Put some load on metrics by creating few alerts and notification groups
3. check different metrics by using following command
`curl localhost:8090/admin/prometheus | grep your_metric`
[local-server-prom-logs.txt](https://github.com/user-attachments/files/17929888/local-server-prom-logs.txt)

[notification] Make timers dynamic per namespace

---

kubernetes/helm/startree-thirdeye/templates/_helpers.tpl
kubernetes/helm/startree-thirdeye/templates/coordinator/deployment.yaml
kubernetes/helm/startree-thirdeye/templates/scheduler/deployment.yaml
kubernetes/helm/startree-thirdeye/templates/worker/deployment.yaml

[k8s - force 2 procs to JVM when cpu.requests <= 1000](https://startree.atlassian.net/browse/TE-2558)
For small or lightly used environments, we'd like to have cpu.requests<=1000m. 
Problem when we do this is java thinks there is only one proc and this hurts the parallel computation capabilities, especially in the simple create flow
Java behaviour based on cpu.requests
- Up to 1000m: 1 proc
-  1001-2000m: 2 procs
-  2001-3000m: 3 procs
When cpu.requests is smaller than or equal to 1000m, we should pass the argument 
`-XX:ActiveProcessorCount=2`
This PR adds the logic to dynamically pass this argument in JAVA_OPTS of coordinator / scheduler / worker deployments based on the cpu request count
Tested via helm install dry run with different values for cpu requests of coordinator, scheduler …

[helm] force 2 procs to JVM when cpu.requests <= 1000

---

thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/ThirdEyeIntegrationTestSupport.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/TaskManagerImpl.java

* [persistence] refresh task metrics every 30 seconds
* [persistence] add task acquisition latency
unrelated but experienced in the PR automated tests:
* [integration-tests] make tests less flacky by isolating test dbs

[persistence] refresh task metrics every 30 seconds

---

kubernetes/helm/startree-thirdeye/templates/_helpers.tpl

[k8s - force 2 procs to JVM when cpu.requests <= 1000](https://startree.atlassian.net/browse/TE-2558)
In #1693, we added logic to dynamically pass this argument in JAVA_OPTS of coordinator / scheduler / worker deployments based on the cpu request count
Current helm installation in startree-platform doesn't support [mulf](https://helm.sh/docs/chart_template_guide/function_list/#mulf) function
This PR modifying the helper method to avoid using mulf
Tested via helm install dry run with different values for cpu requests of coordinator, scheduler and workers
`helm install startree-thirdeye --dry-run --debug --generate-name --set coordinator.resources.requests.cpu=<coordinator-cpu> --set scheduler.resources.requests.cpu=<scheduler-cpu> --set worker.resources.requests.cpu=<worker-cpu>`
| …

[helm] Improve helper logic to avoid using mulf

---

kubernetes/helm/startree-thirdeye/templates/_helpers.tpl

fix helm failure when requests.cpu is an int. eg `requests.cpu:2`
```
helm template startree-thirdeye  --set coordinator.resources.requests.cpu=1 --set scheduler.resources.requests.cpu=0.5 --set worker.resources.requests.cpu=2 
```
```
helm template startree-thirdeye  --set coordinator.resources.requests.cpu=100m --set scheduler.resources.requests.cpu=1000m --set worker.resources.requests.cpu=2000m
```

[k8s] fix lessOrEqualTo1Cpu when cpu input is of type int

---

thirdeye-detectionpipeline/src/main/java/ai/startree/thirdeye/detectionpipeline/persistence/DelegateDatasetConfigManager.java
thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/arch/ArchitectureTest.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AbstractManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AlertManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AnomalyManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/EventManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/RcaInvestigationManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/SubscriptionGroupManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/TaskManagerImpl.java
thirdeye-scheduler/src/main/java/ai/startree/thirdeye/scheduler/SchedulerService.java
thirdeye-server/src/main/java/ai/startree/thirdeye/ThirdEyeServer.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/bao/AbstractManager.java

Some metrics are based on queries run on the MySql instance. 
As of today they are registered when DAO singletons are instantiated. 
This means they are registered for all components of ThirdEye. (coordinator, scheduler, worker).
This causes two issues: 
- it is confusing
- because there is a cache, the value of the metric may not match between components. The difference can be huge.
- when writing prometheus queries, one must be wary of not aggregating the same thing twice
- when scaling workers or coordinators, the number of metrics queries scale linearly. It should not.
This PR implements logic to only have the scheduler collect the expensive database-based metrics.
A log is added to make it simple to check if the metrics are registered correctly:
```
INFO  [2024-11-28 16:15:29,616] …
```

[server] make only the scheduler register expensive database metrics

---

thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverRunnable.java

ThirdEye workers have multiple threads.
for the benchmarks, we need to measure idle times per thread.
Add thread as a tag to the idle and sleep metrics. 
The threads are properly named, see https://github.com/startreedata/thirdeye/blob/f9d99e3939afd9bf5e195afc719388b55c0b71bb/thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverThreadPoolManager.java#L47

[worker] add thread name to sleep metrics

---

thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/dao/TestNamespaceConfigurationDao.java

[Time configuration - introduce namespace configuration entity](https://startree.atlassian.net/browse/TE-2447)
Test order constraints is not correct in TestNamespaceConfigurationDao and makes test flaky based on the order in which independent tests are run
This PR fixes the tests logic by making sure their affected entities don't coincide such that each independent test can run in any order

[persistence] Fix flaky NamespaceConfigurationDao tests

---

thirdeye-core/src/main/java/ai/startree/thirdeye/datasource/cache/DataSourceCache.java

getDataSource can throw exceptions
with the previous implementation, any exception was breaking the metric. 
change: catch the exception

[core] fix datasource metric gets broken in case of incorrect datasource configuration

---

thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AnomalyManagerImpl.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/bao/AnomalyManager.java

update temporary code paths that could result in OOM when the number of anomalies for many alerts is high and multiple stats call are performed concurrentl (this can happen in the landing page)

[persistence] remove namespace migration logic that could cause oom in edge cases

---

thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/DatabaseClient.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/TaskManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/dao/GenericPojoDao.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/dao/NamespaceConfigurationDao.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/dao/TaskDao.java
thirdeye-persistence/src/test/java/ai/startree/thirdeye/datalayer/bao/TestAnomalyTaskManager.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/DatabaseAdminResource.java
thirdeye-server/src/main/java/ai/startree/thirdeye/service/DatabaseAdminService.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/datalayer/bao/TaskManager.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverRunnable.java

See https://startree.atlassian.net/browse/TE-2579
Fix DatabaseClient exception throwing design. DatabaseClient does not catch exception anymore, it's the consumer that is responsible for catching the error. 
From what I saw having the DAOs catching error is still not a good design because they log the errorn, replace with an error values (0, null), and then the consumer still has to perform an argument/state check on the error value. If an error value is encountered, the an exception is thrown but it does not contain the stack of the original error anymore.
This can be taken in another PR. 
Has the effect of fixing the issue of `TaskManager(Impl).acquireNextTaskToRun` not surfacing errors because they were caught by the DatabaseClient, ie it fixes a task scheduler bug. …

[persistence] remove exception catch in DatabaseClient

---

thirdeye-core/src/main/java/ai/startree/thirdeye/datasource/cache/DataSourceCache.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AlertManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/AnomalyManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/RcaInvestigationManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/SubscriptionGroupManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/TaskManagerImpl.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/Constants.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/util/MetricsUtils.java

some metrics are expensive to compute
with `memoizeWithExpiration`, the computation is performed when the prometheus endpoint is hit.
if there are many metrics supplier that expired at the same time (which is very likely), the computation is triggered for all these metrics at the same time. This is stressing the db and also result in prometheus parse timeout.  
This PR introduce a helper to schedule the refresh of a metric instead of waiting for the prometheus hit. Some random delay is added to spread the request load (the spread may not be optimal but it's ok to begin with)  
Let me know what you think.

[persistence] optimize db metrics caching by scheduling and spreading refresh load

---

thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotQueryExecutor.java
thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotThirdEyeDataSource.java
thirdeye-server/src/main/java/ai/startree/thirdeye/core/ExceptionHandler.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/ThirdEyeStatus.java

[Surface the pinot quota error properly](https://startree.atlassian.net/browse/TE-2580)
Currently, there are several problems in how pinot exceptions are caught and surfaced.
1. Errors thrown by PinotQueryExecutor's [load()](https://github.com/startreedata/thirdeye/blob/302335a30554a628eb1ce5f20d63991d8e71ae07/thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotQueryExecutor.java#L216) method are not caught properly in the [caller code](https://github.com/startreedata/thirdeye/blob/302335a30554a628eb1ce5f20d63991d8e71ae07/thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/PinotThirdEyeDataSource.java#L161) because any exception thrown in load method of a guava cache is wrapped around by …

[server] Handle PinotClientException in exception handler

---

thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/TaskManagerImpl.java
thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/dao/TaskDao.java
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/TaskDriverRunnable.java

See https://startree.atlassian.net/browse/TE-2586
We can skip the first heartbeat by setting the `lastActive` value at acquisition directly. 
this saves 2 queries for all task that run faster than the heartbeat frequency. 
For most detection, this means the number of queries per task is reduced by 2.
At high scale this matters. The heartbeat queries take locks.
Note:
the heartbeat logic is still bad because it has a concurrency issue but this will be taken in another PR. See https://startree.atlassian.net/browse/TE-2578

[persistence] optimize first heartbeat

---

thirdeye-ui/src/app/components/anomaly-feedback/anomaly-feedback.component.tsx
thirdeye-ui/src/app/components/anomaly-feedback/modal/anomaly-feedback-modal.component.tsx
thirdeye-ui/src/app/utils/anomalies/anomalies.util.ts

https://startree.atlassian.net/browse/TE-2572
When user was clicking on either of the options, "No this is not an anomaly" or "Yes this is an anomaly", in the confirmation modal, radio options text was not visible.

fix(ui): TE-2572 fix radio options not showing in anomaly confirmation modal

---

jacoco-code-coverage/pom.xml
pom.xml
thirdeye-integration-tests/pom.xml

[[BE] Apps Team Testing & Secure CI Update - V1 (Manual)](https://startree.atlassian.net/browse/AI-18)
This PR adds basic jacoco code coverage local setup
1. `./mvnw clean verify`
2. Check aggregate coverage report in 
```jacoco-code-coverage/target/site/jacoco-aggregate/index.html```
Also verified that maven release doesn't break by a local run
```
./mvnw clean -B -DskipTests -Darguments=-DskipTests release:clean initialize release:prepare -U
```
Output:
[thirdeye-release-logs.txt](https://github.com/user-attachments/files/18151998/thirdeye-release-logs.txt)

Add Jacoco Code Coverage support

---

thirdeye-ui/src/app/components/time-range/past-duration-picker/past-duration-picker.component.tsx

https://startree.atlassian.net/browse/TE-2594
Users were able to add negative value for time period to compare in anomaly view page, which was crashing the app.
Added a check so that only positive values are allowed

fix(ui): TE-2594 do not allow negative value for time period compare in anomaly view

---

thirdeye-server/src/main/java/ai/startree/thirdeye/auth/AuthorizationManager.java

[Make AuthorizationManager a Singleton to improve memory footprint](https://startree.atlassian.net/browse/TE-2607)
Ideally AuthorizationManager should be a singleton but currently that is not enforced
which results into higher memory footprint and instance duplication
1. Run local thirdeye debug server
2. Find PID of running server -> `ps aux | grep java`
3. Run `jmap -histo <PID> | grep ai.startree.thirdeye.auth.AuthorizationManager`
| Before  | After |
| ------------- | ------------- |
| [before-jmap.txt](https://github.com/user-attachments/files/18196286/before-jmap.txt)  | [after-jmap.txt](https://github.com/user-attachments/files/18196287/after-jmap.txt) |
**How to interpret output:**
Column 1: Rank (Index) -> The rank of the class in terms of the number of instances
Column 2: Number …

[server] Make AuthorizationManager class a Singleton

---

thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/dao/TaskDao.java

Add `FORCE INDEX (task_status_idx)`
to force the usage of the index primary key in the `SORT BY id LIMIT 1` operation.
Without this hint, the engine decides to sort in memory instead of using the index structure, which is ok when the number of WAITING tasks is small but gets more expensive when the number of WAITING tasks is big.
Overhead when the waiting tasks is small is fine.
Measurements on a stressed instance with 7k tasks with `status = 'WAITING'`: 
```
mysql> select *  from task_entity WHERE status = 'WAITING'  AND ref_id not in (select ref_id from task_entity where status = 'RUNNING') ORDER BY id ASC LIMIT 1 FOR UPDATE SKIP LOCKED;
+---------+----------------+---------+-----------+------------+----------+--------+-----------+---------------------+---------------------+---------+--- …
```

[persistence] optimize task acquisition query

---

.github/workflows/fe-e2e.yaml
thirdeye-ui/cypress/fixtures/example.json
thirdeye-ui/cypress/support/commands.ts
thirdeye-ui/cypress/support/e2e.ts
thirdeye-ui/e2e/pages/alert-detail.ts
thirdeye-ui/e2e/pages/base.ts
thirdeye-ui/e2e/pages/create-alert.ts
thirdeye-ui/e2e/pages/home.ts
thirdeye-ui/e2e/pages/onboarding.ts
thirdeye-ui/e2e/tests/alert-details.spec.ts
thirdeye-ui/e2e/tests/anomalies.spec.ts
thirdeye-ui/e2e/tests/create-alert.spec.ts
thirdeye-ui/e2e/tests/onboarding.spec.ts
thirdeye-ui/src/app/components/additional-filters-drawer/additional-filters-drawer.component.tsx
thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx

E2E tests - Create alert

---

pinot-test-container/src/main/java/org/apache/pinot/testcontainer/PinotContainer.java
scripts/load-datasets.sh
scripts/start-pinot.sh
thirdeye-ui/src/test/e2e/helper-scripts/docker-compose.yaml
thirdeye-ui/src/test/e2e/helper-scripts/launch_fresh_be_with_current_fe.py

[Update Pinot Version to 1.2.0](https://startree.atlassian.net/browse/TE-2614)
Pinot 1.1.0 is not available anymore on: 
https://downloads.apache.org/pinot/

chore(ui): TE - Update pinot version to 1.2.0

---

thirdeye-server/src/main/java/ai/startree/thirdeye/service/alert/AlertInsightsProvider.java
thirdeye-spi/src/main/java/ai/startree/thirdeye/spi/api/AlertInsightsApi.java

A dataset can return suspicious start times, like very small negative numbers for something that is expected to be an epoch. 
Add logic to manage this case.
For the moment we only set a minimum of 0 and report the suspicious start time.

[server] add suspiciousDatasetStartTime to insights api when start time is negative

---

thirdeye-plugins/thirdeye-pinot/src/main/java/ai/startree/thirdeye/plugins/datasource/pinot/resultset/AbstractThirdEyeResultSet.java

Pinot can return special primitive values that mean null.
For instance Pinot can return `Long.MIN_VALUE`.
ThirdEye uses the same value for null in dataframe Series implementation, this resulted in unexpected null errors.
Add a dedicated code path to log this use case.
It's a legit behavior, but in most cases it's symptomatic of a data issue, so it is logged with WARN level.

[pinot] fix primite null value edge case

---

kubernetes/helm/startree-thirdeye/templates/coordinator/configmap.yaml

[upgrade qps quota in Pinot table when table is onboarded in TE](https://startree.atlassian.net/browse/TE-2505)
Adding quotas to helm template configuration
It is used to enable the feature to override the default pinot max QPS quota for the tables that are being onboarded to TE (#1741)
Validate helm install locally
`cd kubernetes/helm/startree-thirdeye`
`helm install --generate-name . --debug --dry-run`
[helm-debug-output-log-plain.txt](https://github.com/user-attachments/files/18361263/helm-debug-output-log-plain.txt)
`helm install --generate-name . --debug --dry-run --set quotas.pinotMaxQPSQuotaOverride=100`
[Uploading helm-debug-output-log-override.txt…]()

[k8s] Add quotas to helm template

---

thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx

https://startree.atlassian.net/browse/TE-2617
In alert create flow, on updating date range, evaluate call was not taking template properties in account. Fixed in this PR

fix(ui): TE-2617 fix evaluate API error in create alert flow on date range change

---

thirdeye-scheduler/src/main/java/ai/startree/thirdeye/scheduler/DetectionCronScheduler.java
thirdeye-scheduler/src/main/java/ai/startree/thirdeye/scheduler/SubscriptionCronScheduler.java
thirdeye-scheduler/src/main/java/ai/startree/thirdeye/scheduler/TaskCronSchedulerRunnable.java
thirdeye-scheduler/src/main/java/ai/startree/thirdeye/scheduler/ThirdEyeSchedulerConfiguration.java

[thirdeye tasks limit per month](https://startree.atlassian.net/browse/TE-2603)
[ThirdEye Free Tier Usage Quota
](https://docs.google.com/document/d/10UK1rLjSnwoe-gIKy9K7erOM_1DpMaNOHsGn9jgQ4AM/edit?tab=t.0#heading=h.2k2bjxgh7f56)
#1751 introduced TaskQuotasConfiguration as part of workspace configuration
This PR adds the core logic to incorporate task quotas in the job scheduler for both DETECTION and NOTIFICATION tasks
It computes, for each workspace, if it has exceeded the DETECTION/NOTIFICATION monthly task quota
If yes, then it stops the currently running jobs and does not let any new job get scheduled
e2e tests are out of scope, will be done in another PR.
Manually tested locally with following data
Related server.yaml config:
```
defaultWorkspaceConfiguration:
...
... …
```

[scheduler] Add core logic to accomodate monthly tasks limit

---

kubernetes/helm/startree-thirdeye/templates/coordinator/configmap.yaml
kubernetes/helm/startree-thirdeye/templates/scheduler/scheduler-config.yaml
kubernetes/helm/startree-thirdeye/templates/worker/worker-config.yaml
kubernetes/helm/startree-thirdeye/values.yaml

[thirdeye tasks limit per month](https://startree.atlassian.net/browse/TE-2603)
Adding namespaceQuotasConfiguration to helm templates
[ThirdEye Free Tier Usage Quota
](https://docs.google.com/document/d/10UK1rLjSnwoe-gIKy9K7erOM_1DpMaNOHsGn9jgQ4AM/edit?tab=t.0#heading=h.2k2bjxgh7f56)
It is used to enable the feature to set monthly quota for detection and notification tasks per namespace 
Validate helm install locally
`cd kubernetes/helm/startree-thirdeye`
`helm install --generate-name . --debug --dry-run`
[helm-install-default.txt](https://github.com/user-attachments/files/18477207/helm-install-default.txt)
`helm install --generate-name . --debug --dry-run --set defaultWorkspaceConfiguration.namespaceQuotasConfiguration.taskQuotasConfiguration.maximumDetectionTasksPerMonth=3100 --set …

[k8s] Add namespaceQuotasConfiguration to helm template

---

.github/workflows/fe-e2e.yaml
thirdeye-ui/e2e/pages/alert-detail.ts
thirdeye-ui/e2e/pages/alert-list.ts
thirdeye-ui/e2e/tests/alert-details.spec.ts
thirdeye-ui/src/app/components/time-range/time-range-selector/time-range-selector/time-range-selector.interfaces.ts
thirdeye-ui/src/app/pages/alerts-view-page/alerts-view-page.component.tsx

https://startree.atlassian.net/browse/TE-2635
Chart data was not loading when user was updating the date range in alert details page.

fix(ui): TE-2635 fix chart load issue on date change in alert details

---

thirdeye-ui/src/app/pages/alerts-create-page/alerts-create-easy-page/alerts-create-easy-page.component.tsx
thirdeye-ui/src/app/pages/rca/investigation-state-tracker-container-page/investigation-state-tracker.component.tsx
thirdeye-ui/src/app/pages/welcome-page/create-datasource/onboard-datasource/onboard-datasource-page.component.tsx

https://startree.atlassian.net/browse/TE-2637

fix(ui): TE-2637 free tier feedback

---

thirdeye-plugins/thirdeye-detectors/src/main/java/ai/startree/thirdeye/plugins/detectors/ThresholdRuleDetector.java
thirdeye-plugins/thirdeye-detectors/src/main/java/ai/startree/thirdeye/plugins/detectors/ThresholdRuleDetectorSpec.java
thirdeye-plugins/thirdeye-detectors/src/test/java/ai/startree/thirdeye/plugins/detectors/ThresholdRuleDetectorTest.java

add `maxInclusive`, `minInclusive` to threshold to control whether the max/min value is detected as an anomaly or not.

[detectors] add inclusive flag to threshold boundaries

---

thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/AnomalyResolutionTest.java
thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/SchedulingTest.java
thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/TestNotificationServiceFactory.java
thirdeye-integration-tests/src/test/resources/anomalyresolution/payloads/alert-1.json
thirdeye-integration-tests/src/test/resources/anomalyresolution/payloads/subscription-group.json
thirdeye-notification/src/main/java/ai/startree/thirdeye/notification/NotificationTaskFilter.java
thirdeye-persistence/src/test/java/ai/startree/thirdeye/aspect/CronTriggerImplAspect.java
thirdeye-persistence/src/test/resources/META-INF/aop.xml
thirdeye-worker/src/main/java/ai/startree/thirdeye/worker/task/runner/DetectionPipelineTaskRunner.java

This PR makes the behavior of the QuartzScheduler simpler to understand when the time is mocked in e2e tests. 
When the time is mocked, time can jump and the quartz scheduler can miss cron triggers. 
See 
- https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-04.html#:~:text=A%20misfire%20occurs%20if%20a,pool%20for%20executing%20the%20job.
- https://nurkiewicz.com/2012/04/quartz-scheduler-misfire-instructions.html and 
- read the code of `org.quartz.simpl.RamJobStore`, `org.quartz.core.QuartzSchedulerThread` and `org.quartz.impl.triggers.CronTriggerImpl`
Previously the logic applied for the cron trigger schedules created [here](https://github.com/startreedata/thirdeye/blob/713d3b4f9b61320103f6f8955f4d4047c2daf61c/thirdeye-scheduler/src/main/java/ai/startree …

[persistence] improve time mock for quartz scheduler

---

thirdeye-ui/e2e/pages/anomaly-view.ts
thirdeye-ui/src/app/components/anomalies-view/feedback-collector/feedback-collector.component.tsx
thirdeye-ui/src/app/pages/anomalies-view-page/anomalies-view-validate-page.component.tsx

https://startree.atlassian.net/browse/TE-2643
Remove the button to compare previous period on anomaly view page

fix(ui): TE-2643 remove previous period compare btn

---

thirdeye-ui/src/app/pages/anomalies-all-page/anomalies-all-page.component.tsx
thirdeye-ui/src/app/rest/anomalies/anomalies.rest.ts
thirdeye-ui/src/app/rest/anomalies/anomaly.interfaces.ts

https://startree.atlassian.net/browse/TE-2647
When filtering anomalies to include more than one alert, the anomalies for the second alert don’t show up in the anomaly list.
API call is only taking first alert in the account.

fix(ui): TE-2647 anomaly list filter with multiple alert fix

---

thirdeye-ui/src/app/locale/languages/en-us.json
thirdeye-ui/src/app/pages/create-alert/hooks/state/index.tsx
thirdeye-ui/src/app/pages/create-alert/sections/aggregation-granularity-detection/detection/index.tsx
thirdeye-ui/src/app/pages/create-alert/sections/aggregation-granularity-detection/detection/multiple-dimension/recommended-dimesions-modal.tsx
thirdeye-ui/src/app/pages/create-alert/sections/aggregation-granularity-detection/detection/multiple-dimension/sql-query-view.tsx
thirdeye-ui/src/app/pages/create-alert/sections/aggregation-granularity-detection/granularity.tsx
thirdeye-ui/src/app/pages/create-alert/sections/dataset-metric-selection/index.tsx
thirdeye-ui/src/app/pages/create-alert/sections/view-alert-graph/graph-options/detection-algorithm.tsx
thirdeye-ui/src/app/utils/datasources/use-get-datasources-tree.util.ts

fix(ui): TE-XXXX show loader for alert recommendations

---

thirdeye-integration-tests/src/test/java/ai/startree/thirdeye/HappyPathTest.java
thirdeye-server/src/main/java/ai/startree/thirdeye/resources/AlertResource.java
thirdeye-server/src/main/java/ai/startree/thirdeye/service/AlertService.java
thirdeye-server/src/main/java/ai/startree/thirdeye/service/alert/AlertInsightsProvider.java

Frontend currently calls `alerts/insights` endpoint via 2 ways:
1. On create alert page, when user has selected upto granularity, this API is called with alert configuration (without id) to get insights
2. On alert details page, this API is called with just the alert Id.
This PR -> 
1. Cleans up deprecated `alerts/{id}/insights` endpoint
2. Handles both cases in `alerts/insights` endpoint
a -> if the id is set, id takes precedence, we fetch the entity from the db
b -> if the id is not set, we use the fields passed in the payload

[server] remove deprecated insights endpoint by alert id

---

thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/dao/GenericPojoDao.java

[Investigate and fix anomalies list API slow response](https://startree.atlassian.net/browse/TE-2650)
Optimizes parsing logic of query result in getV2 method of GenericPojoDao

[persistence] Optimize result parsing in GenericPojoDao::getV2

---

thirdeye-persistence/src/main/java/ai/startree/thirdeye/datalayer/bao/NamespaceConfigurationManagerImpl.java

Currently, if somehow namespace configuration goes into an invalid state, multiple parts of the system might break
and we don't have a dedicated alert for tracking this
This PR adds a counter to track all such cases, so that we can create a prometheus alert to get notified of such cases

[persistence] Add counter to track invalid namespace configuration state
